Repository akshitagupta15june/Face-X, pull requests merged in 2021-05, with the labels that each got.

#559 Update Video Background Substarction
  Awesome-face-operations/Video-BG-Substraction/Assets/1_TM1FcHfV1QzlmMM2SKI9SQ.png
  Awesome-face-operations/Video-BG-Substraction/Assets/Figure5_1-1024x690.jpg
  Awesome-face-operations/Video-BG-Substraction/Assets/Image-after-applying-erosion-and-dilation-filter_Q320.jpg
  Awesome-face-operations/Video-BG-Substraction/Assets/Image-before-applying-morphological-filter_Q320 (1).jpg
  Awesome-face-operations/Video-BG-Substraction/Assets/Iot.png
  Awesome-face-operations/Video-BG-Substraction/Assets/VG-logo.png
  Awesome-face-operations/Video-BG-Substraction/Assets/fig1.PNG
  Awesome-face-operations/Video-BG-Substraction/Assets/fig2.PNG
  Awesome-face-operations/Video-BG-Substraction/Assets/fig3.PNG
  Awesome-face-operations/Video-BG-Substraction/Assets/fig4.PNG
  Awesome-face-operations/Video-BG-Substraction/Assets/fig5.PNG
  Awesome-face-operations/Video-BG-Substraction/Assets/fig6.PNG
  Awesome-face-operations/Video-BG-Substraction/Assets/magic-clipper.png
  Awesome-face-operations/Video-BG-Substraction/Assets/remove_image_background.jpg
  Awesome-face-operations/Video-BG-Substraction/readme.md
Labels: Level2, gssoc21

#562 Makeover
  Virtual_makeover/makeover1/images/Makeover1_Original.png
  Virtual_makeover/makeover1/images/README.md
  Virtual_makeover/makeover1/makeover.py
Labels: Level3, gssoc21

#561 Added Face Detection using MTCNN
  Face-Detection/Face Detection using MTCNN/MTCNN.ipynb
  Face-Detection/Face Detection using MTCNN/README.md
  Face-Detection/Face Detection using MTCNN/test1.jpg
Labels: Level3, gssoc21

#563 Issue-445: Added Jupyter file for face restoration from defective photos
  Awesome_Face_Operations/Face_Restoration/Face_Restoration.ipynb
  Awesome_Face_Operations/Face_Restoration/README.md
Labels: Level3, gssoc21

#565 Eyeshadow makeover
  Virtual_makeover/eyeshadow/Input.jpg
  Virtual_makeover/eyeshadow/README.md
  Virtual_makeover/eyeshadow/eyeshadow.py
  Virtual_makeover/eyeshadow/out1.jpg
  Virtual_makeover/eyeshadow/pointeyeshadow.txt
Labels: Level3, gssoc21

#568 Blushing Foundation Makeover
  Virtual_makeover/Foundation_Makeover/Input.jpg
  Virtual_makeover/Foundation_Makeover/README.md
  Virtual_makeover/Foundation_Makeover/foundation.py
  Virtual_makeover/Foundation_Makeover/pointeyes.txt
  Virtual_makeover/Foundation_Makeover/pointface.txt
  Virtual_makeover/Foundation_Makeover/pointlips.txt
Labels: Level3, gssoc21

#567 Added Cartoonify using KMeans
  Cartoonify Image/Cartoonify using KMeans/README.md
  Cartoonify Image/Cartoonify using KMeans/Resources/cartoon.jpg
  Cartoonify Image/Cartoonify using KMeans/Resources/original2.jpg
  Cartoonify Image/Cartoonify using KMeans/Script/cartoonize.py
  Cartoonify Image/Cartoonify using KMeans/Script/vid.py
Labels: Level3, gssoc21

#569 Anti-face spoofing detection
  Awesome-face-operations/Face_Anti-spoofing_detection/Face_Anti-Spoofing_Detection.py
  Awesome-face-operations/Face_Anti-spoofing_detection/README.md
Labels: Level3, gssoc21

#572 Added Image to Pencil Sketch Converter
  Awesome-face-operations/Colorful Sketch Filter/Image to Pencil Sketch/README.md
  Awesome-face-operations/Colorful Sketch Filter/Image to Pencil Sketch/image_to_sketch.py
  Awesome-face-operations/Colorful Sketch Filter/Image to Pencil Sketch/img.jpg
  Awesome-face-operations/Colorful Sketch Filter/Image to Pencil Sketch/img1.jpg
  Awesome-face-operations/Colorful Sketch Filter/Image to Pencil Sketch/img2.jpg
  Awesome-face-operations/Colorful Sketch Filter/Image to Pencil Sketch/img3.jpg
  Awesome-face-operations/Colorful Sketch Filter/Image to Pencil Sketch/img4.jpg
Labels: Level3, gssoc21

#575 Added Emotion Detection using ML
  Face-Emotions-Recognition/Facial Expression Recognition Using ML/Emotion_Recognition_ML.ipynb
  Face-Emotions-Recognition/Facial Expression Recognition Using ML/README.md
  Face-Emotions-Recognition/Facial Expression Recognition Using ML/images/10.png
  Face-Emotions-Recognition/Facial Expression Recognition Using ML/images/8.png
  Face-Emotions-Recognition/Facial Expression Recognition Using ML/images/9.png
  Face-Emotions-Recognition/Facial Expression Recognition Using ML/images/result.png
  Face-Emotions-Recognition/Facial Expression Recognition Using ML/requirements.txt
Labels: Level3, gssoc21

#586 Update readme.md
  Awesome-face-operations/Blurring image across face/readme.md
Labels: Level1, gssoc21

#587 Cowboy Filter
  Snapchat_Filters/CowBoy/README.md
  Snapchat_Filters/CowBoy/cowboy_hat.png
  Snapchat_Filters/CowBoy/haarcascade_frontalface_default.xml
  Snapchat_Filters/CowBoy/main.py
  Snapchat_Filters/CowBoy/moustache.png
  Snapchat_Filters/CowBoy/output.jpg
  Snapchat_Filters/CowBoy/test.jpg
Labels: Level3, gssoc21

#588 Added Vgg-face Implementation
  Recognition-Algorithms/Face Recognition using VGG Face/Face_Recognition.ipynb
  Recognition-Algorithms/Face Recognition using VGG Face/README.md
Labels: Level3, gssoc21

#590 Added flower crown
  CONTRIBUTORS.md
  Snapchat_Filters/Dog_filter/src/__pycache__/step_7_fer.cpython-39.pyc
  Snapchat_Filters/flower_filter/README.md
  Snapchat_Filters/flower_filter/download.png
  Snapchat_Filters/flower_filter/face.xml
  Snapchat_Filters/flower_filter/flower_filter.py
  Snapchat_Filters/flower_filter/pic.png
  Snapchat_Filters/flower_filter/pic1.jpg
  Snapchat_Filters/flower_filter/pic2.jpg
  Snapchat_Filters/flower_filter/requirements.txt
Labels: Level3, gssoc21

#599 Update Readme.md
  Readme.md
Labels: Level0, gssoc21

#602 EXIF orientation
  Awesome-face-operations/Automatic_Rotating_photos/README.md
  Awesome-face-operations/Automatic_Rotating_photos/image_to_numpy/__init__.py
  Awesome-face-operations/Automatic_Rotating_photos/image_to_numpy/src.py
  Awesome-face-operations/Automatic_Rotating_photos/tests/Portrait_8.png
  Awesome-face-operations/Automatic_Rotating_photos/tests/Portrait_no_exif.jpg
  Awesome-face-operations/Automatic_Rotating_photos/tests/test_load_image_file.py
Labels: Level3, gssoc21

#600 Issue 574 Added funny mirror image using opencv
  Awesome-face-operations/Funny-Mirror-Image/FunnyImage.PNG
  Awesome-face-operations/Funny-Mirror-Image/FunnyMirrorImage.py
  Awesome-face-operations/Funny-Mirror-Image/dora.png
  Awesome-face-operations/Funny-Mirror-Image/minion.jpg
  Awesome-face-operations/Funny-Mirror-Image/readme.md
Labels: Level3, gssoc21

#604 Added Witch filter
  Snapchat_Filters/Witch Filter/Pics/Result.png
  Snapchat_Filters/Witch Filter/Pics/witch.png
  Snapchat_Filters/Witch Filter/README.md
  Snapchat_Filters/Witch Filter/Script/facial_test.py
  Snapchat_Filters/Witch Filter/Script/halloween_masks.py
  Snapchat_Filters/Witch Filter/Script/halloween_masks_vid.py
Labels: Level3, gssoc21

#608 Angry Man
  Snapchat_Filters/angry_man/Dataset/Nose18x15.xml
  Snapchat_Filters/angry_man/Dataset/frontalEyes35x16.xml
  Snapchat_Filters/angry_man/Dataset/haarcascade_frontalface_alt.xml
  Snapchat_Filters/angry_man/FilterImages/glasses.png
  Snapchat_Filters/angry_man/FilterImages/mustache.png
  Snapchat_Filters/angry_man/README.md
  Snapchat_Filters/angry_man/Snapchat-Filter.py
Labels: Level3, gssoc21

#610 Added Virtual Makeover
  Virtual_makeover/makeover2/README.md
  Virtual_makeover/makeover2/abcd.jpg
  Virtual_makeover/makeover2/face_recognition/api.py
  Virtual_makeover/makeover2/makeup.py
Labels: Level3, gssoc21

#609 Neon Effect Filter #606
  Awesome-face-operations/Neon Effect Filter/Images/(Neon Effect Filter)image_.jpg
  Awesome-face-operations/Neon Effect Filter/Images/image_.jpg
  Awesome-face-operations/Neon Effect Filter/Neon Effect Filter.py
  Awesome-face-operations/Neon Effect Filter/README.md
Labels: Level3, gssoc21

#614 Glitter Cartoon Filter #611
  Cartoonify Image/Glitter Cartoon Filter/Glitter Cartoon Filter.py
  Cartoonify Image/Glitter Cartoon Filter/Images/Final_Output.jpg
  Cartoonify Image/Glitter Cartoon Filter/Images/Original_image.jpg
  Cartoonify Image/Glitter Cartoon Filter/README.md
Labels: Level3, gssoc21

#628 Flower glasses added
  Snapchat_Filters/Flower_Glasses/Dataset/frontalEyes35x16.xml
  Snapchat_Filters/Flower_Glasses/Dataset/haarcascade_frontalface_alt.xml
  Snapchat_Filters/Flower_Glasses/README.md
  Snapchat_Filters/Flower_Glasses/Snapchat-Filter.py
  Snapchat_Filters/Flower_Glasses/abcd.jpg
  Snapchat_Filters/Flower_Glasses/glasses.png
Labels: Level3, gssoc21

#631 Big Mouth
  Snapchat_Filters/BigMouth/README.md
  Snapchat_Filters/BigMouth/filter.py
  Snapchat_Filters/BigMouth/output.gif
Labels: Level3, gssoc21

#645 Forehead Jewellery Filter #641
  Snapchat_Filters/Festive-Filters/Holi Festival Filter/Code.py
  Snapchat_Filters/Festive-Filters/Holi Festival Filter/Images/Holi Filtered Image.jpg
  Snapchat_Filters/Festive-Filters/Holi Festival Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filters/Holi Festival Filter/Images/holi.png
  Snapchat_Filters/Festive-Filters/Holi Festival Filter/README.md
  Snapchat_Filters/Jewellery Filter/Code.py
  Snapchat_Filters/Jewellery Filter/Images/Fore Head Jewellery.png
  Snapchat_Filters/Jewellery Filter/Images/Image.jpg
  Snapchat_Filters/Jewellery Filter/Images/Jewellery_Filter_Image.jpg
  Snapchat_Filters/Jewellery Filter/Images/earing.png
  Snapchat_Filters/Jewellery Filter/README.md
Labels: Level3, gssoc21

#647 Added Face mask detection using Yolov4
  Face-Mask-Detection/Face mask detection using YOLO V4/README.md
  Face-Mask-Detection/Face mask detection using YOLO V4/mask-detector-image.py
  Face-Mask-Detection/Face mask detection using YOLO V4/output/1_output.jpg
  Face-Mask-Detection/Face mask detection using YOLO V4/utility-scripts/count_objs.py
  Face-Mask-Detection/Face mask detection using YOLO V4/utility-scripts/process_to_txt.py
  Face-Mask-Detection/Face mask detection using YOLO V4/yolov4-mask-detector/obj.data
  Face-Mask-Detection/Face mask detection using YOLO V4/yolov4-mask-detector/obj.names
  Face-Mask-Detection/Face mask detection using YOLO V4/yolov4-mask-detector/yolov4-obj.cfg
Labels: Level3, gssoc21

#661 Eid Festival Filter #646
  Snapchat_Filters/Festive-Filters/Eid Festival Filter/Code.py
  Snapchat_Filters/Festive-Filters/Eid Festival Filter/Images/Eid Filtered Image.png
  Snapchat_Filters/Festive-Filters/Eid Festival Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filters/Eid Festival Filter/Images/eid.png
  Snapchat_Filters/Festive-Filters/Eid Festival Filter/README.md
Labels: Level3, gssoc21

#660 Diwali Festival Filter #643
  Snapchat_Filters/Festive-Filters/Diwali Festival Filter/Code.py
  Snapchat_Filters/Festive-Filters/Diwali Festival Filter/Images/Diwali_Filtered_Image.png
  Snapchat_Filters/Festive-Filters/Diwali Festival Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filters/Diwali Festival Filter/Images/diwali.png
  Snapchat_Filters/Festive-Filters/Diwali Festival Filter/README.md
Labels: Level3, gssoc21

#650 Butterfly_eyes
  Snapchat_Filters/Butterfly_eyes/Dataset/frontalEyes35x16.xml
  Snapchat_Filters/Butterfly_eyes/Dataset/haarcascade_frontalface_alt.xml
  Snapchat_Filters/Butterfly_eyes/README.md
  Snapchat_Filters/Butterfly_eyes/Snapchat-Filter.py
  Snapchat_Filters/Butterfly_eyes/glasses.png
  Snapchat_Filters/Butterfly_eyes/style-5.png
  Snapchat_Filters/FilterImages/glasses.png
Labels: Level3, gssoc21

#662 Anime Eyes
  Snapchat_Filters/Anime_eyes/Dataset/frontalEyes35x16.xml
  Snapchat_Filters/Anime_eyes/Dataset/haarcascade_frontalface_alt.xml
  Snapchat_Filters/Anime_eyes/README.md
  Snapchat_Filters/Anime_eyes/Snapchat-Filter.py
  Snapchat_Filters/Anime_eyes/abcd.jpg
  Snapchat_Filters/Anime_eyes/glasses.png
Labels: Level3, gssoc21

#665 Added Face Detection using YoloV4
  Face-Detection/Face Detection using YOLO V4/Images/download.png
  Face-Detection/Face Detection using YOLO V4/README.md
  Face-Detection/Face Detection using YOLO V4/YoloV4_Notebook.ipynb
Labels: Level3, gssoc21

#663 Tiger Looks
  Snapchat_Filters/Tiger_looks/Dataset/frontalEyes35x16.xml
  Snapchat_Filters/Tiger_looks/Dataset/haarcascade_frontalface_alt.xml
  Snapchat_Filters/Tiger_looks/README.md
  Snapchat_Filters/Tiger_looks/Snapchat-Filter.py
  Snapchat_Filters/Tiger_looks/glasses.png
  Snapchat_Filters/Tiger_looks/style-5.png
Labels: Level3, gssoc21

#667 Heart goggles/crown filter
  Snapchat_Filters/Heart_glasses_crown/README.md
  Snapchat_Filters/Heart_glasses_crown/crown.png
  Snapchat_Filters/Heart_glasses_crown/filter.py
  Snapchat_Filters/Heart_glasses_crown/glasses.png
  Snapchat_Filters/Heart_glasses_crown/requirements.txt
Labels: Level3, gssoc21

#672 Vampire
  Snapchat_Filters/Vampire/Dataset/Nose18x15.xml
  Snapchat_Filters/Vampire/Dataset/frontalEyes35x16.xml
  Snapchat_Filters/Vampire/Dataset/haarcascade_frontalface_alt.xml
  Snapchat_Filters/Vampire/README.md
  Snapchat_Filters/Vampire/Snapchat-Filter.py
  Snapchat_Filters/Vampire/glasses.png
  Snapchat_Filters/Vampire/mustache.png
Labels: Level3, gssoc21

#668 Pirates Filter
  Snapchat_Filters/Pirates Filter/Code.py
  Snapchat_Filters/Pirates Filter/Images/Image.jpg
  Snapchat_Filters/Pirates Filter/Images/hat.png
  Snapchat_Filters/Pirates Filter/Images/moustache.png
  Snapchat_Filters/Pirates Filter/Images/pirate filtered image.png
  Snapchat_Filters/Pirates Filter/Images/pirates.png
  Snapchat_Filters/Pirates Filter/README.md
Labels: Level3, gssoc21

#670 Dussehra Festival Filter #649
  Snapchat_Filters/Festive-Filters/Dussehra Festival Filter/Code.py
  Snapchat_Filters/Festive-Filters/Dussehra Festival Filter/Images/Dussehra Filtered Image.PNG
  Snapchat_Filters/Festive-Filters/Dussehra Festival Filter/Images/Dussehra.png
  Snapchat_Filters/Festive-Filters/Dussehra Festival Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filters/Dussehra Festival Filter/README.md
  Snapchat_Filters/Festive-Filters/Rakshabandhan Festival Filter/Code.py
  Snapchat_Filters/Festive-Filters/Rakshabandhan Festival Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filters/Rakshabandhan Festival Filter/Images/Rakshabandhan Filtered Image.png
  Snapchat_Filters/Festive-Filters/Rakshabandhan Festival Filter/Images/rakshabandhan.png
  Snapchat_Filters/Festive-Filters/Rakshabandhan Festival Filter/README.md
Labels: Level3, gssoc21

#675 Spooky_Makeover
  Virtual_makeover/spooky_makeover/README.md
  Virtual_makeover/spooky_makeover/face_recognition/api.py
  Virtual_makeover/spooky_makeover/makeup.py
  Virtual_makeover/spooky_makeover/style-5.png
Labels: Level3, gssoc21

#679 Lohri Festival Filters #655
  Snapchat_Filters/Festive-Filter/Lohri Festival Filter/Code.py
  Snapchat_Filters/Festive-Filter/Lohri Festival Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filter/Lohri Festival Filter/Images/Lohri Festival Filtered Image.png
  Snapchat_Filters/Festive-Filter/Lohri Festival Filter/Images/Lohri.png
  Snapchat_Filters/Festive-Filter/Lohri Festival Filter/README.md
Labels: Level3, gssoc21

#680 Ganesh Chaturthi Festival Filters #657
  Snapchat_Filters/Festive-Filter/Ganesh Chaturthi Festival Filter/Code.py
  Snapchat_Filters/Festive-Filter/Ganesh Chaturthi Festival Filter/Images/Ganesh Chaturthi Festival Filtered Image.png
  Snapchat_Filters/Festive-Filter/Ganesh Chaturthi Festival Filter/Images/Ganesh Chaturthi.png
  Snapchat_Filters/Festive-Filter/Ganesh Chaturthi Festival Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filter/Ganesh Chaturthi Festival Filter/README.md
Labels: Level3, gssoc21

#678 Independence day Filter #654
  Snapchat_Filters/Festive-Filter/Independence day Filter/Code.py
  Snapchat_Filters/Festive-Filter/Independence day Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filter/Independence day Filter/Images/Independence Day Filtered Image.png
  Snapchat_Filters/Festive-Filter/Independence day Filter/Images/Independence Day.png
  Snapchat_Filters/Festive-Filter/Independence day Filter/README.md
Labels: Level3, gssoc21

#677 Janmashtami Festival Filters #656
  Snapchat_Filters/Festive-Filter/Janmashtami Festival Filter/Code.py
  Snapchat_Filters/Festive-Filter/Janmashtami Festival Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filter/Janmashtami Festival Filter/Images/Janmashtami Festival Filtered Image.png
  Snapchat_Filters/Festive-Filter/Janmashtami Festival Filter/Images/Janmashtami.png
  Snapchat_Filters/Festive-Filter/Janmashtami Festival Filter/README.md
Labels: Level3, gssoc21

#676 Christmas Festival Filter #652
  Snapchat_Filters/Festive-Filter/Christmas Festival Filter/Code.py
  Snapchat_Filters/Festive-Filter/Christmas Festival Filter/Images/Christmas Festival Filtered Image.png
  Snapchat_Filters/Festive-Filter/Christmas Festival Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filter/Christmas Festival Filter/Images/christmas.png
  Snapchat_Filters/Festive-Filter/Christmas Festival Filter/README.md
Labels: Level3, gssoc21

#682 Snake Filter
  Snapchat_Filters/snake/Dataset/frontalEyes35x16.xml
  Snapchat_Filters/snake/Dataset/haarcascade_frontalface_alt.xml
  Snapchat_Filters/snake/README.md
  Snapchat_Filters/snake/Snapchat-Filter.py
  Snapchat_Filters/snake/glasses.png
  Snapchat_Filters/snake/style-6.png
Labels: Level3, gssoc21

#698 Masquerade mask filter
  Snapchat_Filters/Masquerade_mask/README.md
  Snapchat_Filters/Masquerade_mask/masq.png
  Snapchat_Filters/Masquerade_mask/masq_filter.py
  Snapchat_Filters/Masquerade_mask/requirements.txt
Labels: Level3, gssoc21

#697 Added Mask Detection using Yolov2
  Face-Mask-Detection/Face mask detection using YOLO V2/README.md
  Face-Mask-Detection/Face mask detection using YOLO V2/mask-detector-image.py
  Face-Mask-Detection/Face mask detection using YOLO V2/output/1_output.jpg
  Face-Mask-Detection/Face mask detection using YOLO V2/utility-scripts/count_objs.py
  Face-Mask-Detection/Face mask detection using YOLO V2/utility-scripts/process_to_txt.py
  Face-Mask-Detection/Face mask detection using YOLO V2/yolov2-mask-detector/obj.data
  Face-Mask-Detection/Face mask detection using YOLO V2/yolov2-mask-detector/obj.names
  Face-Mask-Detection/Face mask detection using YOLO V2/yolov2-mask-detector/yolov2.cfg
Labels: Level3, gssoc21

#696 Added Face mask detection using Yolov3
  Face-Mask-Detection/Face mask detection using YOLO V3/README.md
  Face-Mask-Detection/Face mask detection using YOLO V3/mask-detector-image.py
  Face-Mask-Detection/Face mask detection using YOLO V3/output/1_output.jpg
  Face-Mask-Detection/Face mask detection using YOLO V3/utility-scripts/count_objs.py
  Face-Mask-Detection/Face mask detection using YOLO V3/utility-scripts/process_to_txt.py
  Face-Mask-Detection/Face mask detection using YOLO V3/yolov3-mask-detector/obj.data
  Face-Mask-Detection/Face mask detection using YOLO V3/yolov3-mask-detector/obj.names
  Face-Mask-Detection/Face mask detection using YOLO V3/yolov3-mask-detector/yolov3.cfg
Labels: Level3, gssoc21

#695 Republic Day Filters #688
  Snapchat_Filters/Festive-Filter/Republic Day Filter/Code.py
  Snapchat_Filters/Festive-Filter/Republic Day Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filter/Republic Day Filter/Images/Republic Day Filtered Image.png
  Snapchat_Filters/Festive-Filter/Republic Day Filter/Images/Republic Day.png
  Snapchat_Filters/Festive-Filter/Republic Day Filter/README.md
Labels: Level3, gssoc21

#694 Durga Puja Festival Filters #689
  Snapchat_Filters/Festive-Filter/Durga Puja Festival Filter/Code.py
  Snapchat_Filters/Festive-Filter/Durga Puja Festival Filter/Images/Durga Puja Festival Filtered Image.png
  Snapchat_Filters/Festive-Filter/Durga Puja Festival Filter/Images/Durga Puja.png
  Snapchat_Filters/Festive-Filter/Durga Puja Festival Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filter/Durga Puja Festival Filter/README.md
Labels: Level3, gssoc21

#693 Chhath Puja Festival Filters #687
  Snapchat_Filters/Festive-Filter/Chhath Puja Festival Filter/Code.py
  Snapchat_Filters/Festive-Filter/Chhath Puja Festival Filter/Images/Chhath Puja Festival Filtered Image.png
  Snapchat_Filters/Festive-Filter/Chhath Puja Festival Filter/Images/Chhath Puja.png
  Snapchat_Filters/Festive-Filter/Chhath Puja Festival Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filter/Chhath Puja Festival Filter/README.md
Labels: Level3, gssoc21

#692 Baisakhi Festival Filters #686
  Snapchat_Filters/Festive-Filter/Baisakhi Festival Filter/Code.py
  Snapchat_Filters/Festive-Filter/Baisakhi Festival Filter/Images/Baisakhi Festival Filtered Image.png
  Snapchat_Filters/Festive-Filter/Baisakhi Festival Filter/Images/Baisakhi.png
  Snapchat_Filters/Festive-Filter/Baisakhi Festival Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filter/Baisakhi Festival Filter/README.md
Labels: Level3, gssoc21

#691 Onam Festival Filters #685
  Snapchat_Filters/Festive-Filter/Onam Festival Filter/Code.py
  Snapchat_Filters/Festive-Filter/Onam Festival Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filter/Onam Festival Filter/Images/Onam Festival Filtered Image.png
  Snapchat_Filters/Festive-Filter/Onam Festival Filter/Images/Onam.png
  Snapchat_Filters/Festive-Filter/Onam Festival Filter/README.md
Labels: Level3, gssoc21

#690 Pongal Festival Filters #683
  Snapchat_Filters/Festive-Filter/Pongal Festival Filter/Code.py
  Snapchat_Filters/Festive-Filter/Pongal Festival Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filter/Pongal Festival Filter/Images/Pongal Festival Filtered Image.png
  Snapchat_Filters/Festive-Filter/Pongal Festival Filter/Images/Pongal.png
  Snapchat_Filters/Festive-Filter/Pongal Festival Filter/README.md
Labels: Level3, gssoc21

#684 Anime face detection and recommendation files added
  Face-Detection/Anime-face-detection-and-recommendation/Notebook.ipynb
  Face-Detection/Anime-face-detection-and-recommendation/anime.csv
  Face-Detection/Anime-face-detection-and-recommendation/readme.md
Labels: Level3, gssoc21

#702 T-Rex_Expression
  Face-X-Gaming/T-rex_expression/README.md
  Face-X-Gaming/T-rex_expression/TRex _Game_with_AR.ipynb
Labels: Level3, gssoc21

#705 Reptile Eyes
  Snapchat_Filters/Reptile/Before.png
  Snapchat_Filters/Reptile/Dataset/frontalEyes35x16.xml
  Snapchat_Filters/Reptile/Dataset/haarcascade_frontalface_alt.xml
  Snapchat_Filters/Reptile/README.md
  Snapchat_Filters/Reptile/Snapchat-Filter.py
  Snapchat_Filters/Reptile/glasses.png
Labels: Level3, gssoc21

#706 Party_Rocks
  Snapchat_Filters/party/Dataset/Nose18x15.xml
  Snapchat_Filters/party/Dataset/frontalEyes35x16.xml
  Snapchat_Filters/party/Dataset/haarcascade_frontalface_alt.xml
  Snapchat_Filters/party/README.md
  Snapchat_Filters/party/Snapchat-Filter.py
  Snapchat_Filters/party/glasses.png
  Snapchat_Filters/party/mustache.png
Labels: Level3, gssoc21

#733 Added Face mask detection using Retinanet
  Face-Mask-Detection/Face-Mask-Detection-using Retinanet/Notebook/Face_Mask_Detection.ipynb
  Face-Mask-Detection/Face-Mask-Detection-using Retinanet/README.md
  Face-Mask-Detection/Face-Mask-Detection-using Retinanet/Results/Test Images/test_img4.png
  Face-Mask-Detection/Face-Mask-Detection-using Retinanet/Results/Test Images/test_img8.png
Labels: Level3, gssoc21

#741 Outline Filter #681
  Snapchat_Filters/Outline_Filter/Outline_filter.py
  Snapchat_Filters/Outline_Filter/README.MD
  Snapchat_Filters/Outline_Filter/images/inp_img1.jpg
  Snapchat_Filters/Outline_Filter/images/inp_img2.jpg
  Snapchat_Filters/Outline_Filter/images/out_img1.jpg
  Snapchat_Filters/Outline_Filter/images/out_img2.jpg
  Snapchat_Filters/Outline_Filter/requirements.txt
Labels: Level3, gssoc21

#732 Added Face Mask Detection using Xception
  Face-Mask-Detection/Face-Mask-Detection-using Xception/Notebook/Face_Mask_Detection.ipynb
  Face-Mask-Detection/Face-Mask-Detection-using Xception/README.md
  Face-Mask-Detection/Face-Mask-Detection-using Xception/Results/Test Images/test_img1.png
  Face-Mask-Detection/Face-Mask-Detection-using Xception/Results/Test Images/test_img9.png
Labels: Level3, gssoc21

#734 Birthday Filter added
  Snapchat_Filters/Bday_Filter/Bday_Filter.py
  Snapchat_Filters/Bday_Filter/README.md
  Snapchat_Filters/Bday_Filter/hat.png
  Snapchat_Filters/Bday_Filter/horn.png
  Snapchat_Filters/Bday_Filter/requirements.txt
Labels: Level3, gssoc21

#746 Tears_Filter added
  Snapchat_Filters/Tears_Filters/README.md
  Snapchat_Filters/Tears_Filters/Tears_filter.py
  Snapchat_Filters/Tears_Filters/requirements.txt
  Snapchat_Filters/Tears_Filters/tear left.png
  Snapchat_Filters/Tears_Filters/tear right.png
Labels: Level3, gssoc21

#775 Added Mask detection using Transfer Learning
  Face-Mask-Detection/Face-Mask-Detection using Transfer Learning/Face Mask Final.ipynb
  Face-Mask-Detection/Face-Mask-Detection using Transfer Learning/README.md
  Face-Mask-Detection/Mask detection using MTCNN/README.md
  Face-Mask-Detection/Mask detection using MTCNN/main.py
  Face-Mask-Detection/Mask detection using MTCNN/requirements.txt
  Face-Mask-Detection/Mask detection using MTCNN/test/results/0200b38c89b16c37c5de8e247bb00c2f.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/101d6660a8974050b613dd2e6bd59390.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/1125506397_15801322207531n.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/1155x768_20200129000089.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/1197315184.jpg.0.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/1224331650.g_400-w_g.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/1579924271.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/1580166133-5b61094cac11561b0cbe09826e32a924.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/3FED248000000578-0-image-a-13_1493884143646.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/5e353e347af50726986e84c0.jpeg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/5e476cd4cd34a.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/64d0947f-6fb5-4d47-9bf3-33f9110274bf_m.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/76bda8e5-edf5-4f0c-8868-4cec4b413c00883e5a2b-7fff-4ae0-88d2-e9b7f1cf24c0.jpeg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/77dd852cd97644dbb37570d1a4ad33e6_18.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/843b3ea7c0eb9b80617cdac8d95afc0e.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/960x0.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/9e6bf0fbabfbde89c74bff7e25af86b3.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/AP20027208528038.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/AP_20039189423521.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/B612_20200127_155432_958.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/B9722327986Z.1_20200123111831_000+GO0FC0I8E.2-0.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/Coronavirus-China.jpeg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/GettyImages-1197620885.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/Hong-Kong-Flu.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/PHOTriZgIKIgsnNLdBJG75vj200203_1000x2000.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/article-5e3820ca235ef.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/coronavirus.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/d3144235.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/d6c103ca-7ec5-450f-9243-27663bcb4deb_0.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/depositphotos_196900844-stock-photo-mother-wearing-protective-mask-daughter.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/fjkllllg.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/gettyimages-491638349-1024x1024.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/https___s3-ap-northeast-1.amazonaws.com_psh-ex-ftnikkei-3937bb4_images_5_7_7_5_24475775-4-eng-GB_Cropped-1579277753mask 2.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/pollution-mask-CE5HYF.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/r1p00017o8171pnq407.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/r1p00017o8357s6sno6.jpg
  Face-Mask-Detection/Mask detection using MTCNN/test/results/recall.png
  Face-Mask-Detection/Mask detection using MTCNN/test/run_tests.py
  Face-Mask-Detection/Mask detection using MTCNN/test/utils/__init__.py
  Face-Mask-Detection/Mask detection using MTCNN/test/utils/detections.py
  Face-Mask-Detection/Mask detection using MTCNN/test/utils/metrics.py
  Face-Mask-Detection/Mask detection using MTCNN/test/utils/parser.py
  Face-Mask-Detection/Mask detection using MTCNN/utils/detections.py
  Face-Mask-Detection/Mask detection using MTCNN/utils/drawing.py
  Face-Mask-Detection/Mask detection using MTCNN/utils/tracking.py
Labels: Level3, gssoc21

#772 Silly-Face
  Snapchat_Filters/silly-face/Dataset/frontalEyes35x16.xml
  Snapchat_Filters/silly-face/Dataset/haarcascade_frontalface_alt.xml
  Snapchat_Filters/silly-face/README.md
  Snapchat_Filters/silly-face/Snapchat-Filter.py
  Snapchat_Filters/silly-face/abcd.jpg
  Snapchat_Filters/silly-face/glasses.png
Labels: Level3, gssoc21

#787 Magazine filter added
  Snapchat_Filters/Magazine_filter/README.md
  Snapchat_Filters/Magazine_filter/magazine.py
  Snapchat_Filters/Magazine_filter/requirements.txt
  Snapchat_Filters/Magazine_filter/time.png
Labels: Level3, gssoc21

#790 MS Paint filter uploaded
  Snapchat_Filters/Aesthetic_MSpaint/README.md
  Snapchat_Filters/Aesthetic_MSpaint/paint.png
  Snapchat_Filters/Aesthetic_MSpaint/paint.py
  Snapchat_Filters/Aesthetic_MSpaint/requirements.txt
Labels: Level3, gssoc21

#794 World Water Day Filter #786
  Snapchat_Filters/Festive-Filter/World Water Day Filter/Code.py
  Snapchat_Filters/Festive-Filter/World Water Day Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filter/World Water Day Filter/Images/Water Day.png
  Snapchat_Filters/Festive-Filter/World Water Day Filter/Images/World Water Day Filtered Image.png
  Snapchat_Filters/Festive-Filter/World Water Day Filter/README.md
Labels: Level3, gssoc21

#780 Lazer-eyes
  Virtual_makeover/Lazer_Eyes/README.md
  Virtual_makeover/Lazer_Eyes/abcd.jpg
  Virtual_makeover/Lazer_Eyes/face_recognition/api.py
  Virtual_makeover/Lazer_Eyes/makeup.py
  Virtual_makeover/face_recognition/api.py
Labels: Level3, gssoc21

#779 Added Rainbow_filter
  Snapchat_Filters/Glasses on face/Face_glasses.py
  Snapchat_Filters/Rainbow_filter/Mouth.xml
  Snapchat_Filters/Rainbow_filter/README.md
  Snapchat_Filters/Rainbow_filter/Rainbow_filter.py
  Snapchat_Filters/Rainbow_filter/face.xml
  Snapchat_Filters/Rainbow_filter/haarcascade_frontalface_default.xml
  Snapchat_Filters/Rainbow_filter/images.jpg
  Snapchat_Filters/Rainbow_filter/pic2.png
  Snapchat_Filters/Rainbow_filter/requirements.txt
  Snapchat_Filters/flower_filter/flower_filter.py
Labels: Level3, gssoc21

#764 Beard Filter Added
  Snapchat_Filters/Beard Filter/Beard_Filter.py
  Snapchat_Filters/Beard Filter/README.md
  Snapchat_Filters/Beard Filter/beard.png
  Snapchat_Filters/Beard Filter/requirements.txt
Labels: Level3, gssoc21

#771 Maha Shivratri Festival Filters #709
  Snapchat_Filters/Festive-Filter/Maha Shivratri Festival Filters/Code.py
  Snapchat_Filters/Festive-Filter/Maha Shivratri Festival Filters/Images/Image.jpg
  Snapchat_Filters/Festive-Filter/Maha Shivratri Festival Filters/Images/Maha Shivratri Festival Filtered Image.png
  Snapchat_Filters/Festive-Filter/Maha Shivratri Festival Filters/Images/Maha Shivratri.png
  Snapchat_Filters/Festive-Filter/Maha Shivratri Festival Filters/README.md
Labels: Level3, gssoc21

#835 Math formulae filter
  Snapchat_Filters/Maths_formulae_filter/README.md
  Snapchat_Filters/Maths_formulae_filter/maths.py
  Snapchat_Filters/Maths_formulae_filter/mm.png
  Snapchat_Filters/Maths_formulae_filter/requirements.txt
Labels: Level3, gssoc21
