Repository akshitagupta15june/Face-X, pull requests merged in 2021-06, with the labels that each got.

#853 Confused Face Filter
  Snapchat_Filters/Confused Face Filter/Code.py
  Snapchat_Filters/Confused Face Filter/Images/Confused Face Filtered Image.png
  Snapchat_Filters/Confused Face Filter/Images/Eyes.png
  Snapchat_Filters/Confused Face Filter/Images/Image.jpg
  Snapchat_Filters/Confused Face Filter/Images/Mouth.png
  Snapchat_Filters/Confused Face Filter/README.md
Labels: Level3, gssoc21

#847 Added Face Detection using Probabilistic modeling
  Face-Detection/Face detection using probabilistic-modelling/Adaboost/ada_boost.py
  Face-Detection/Face detection using probabilistic-modelling/Adaboost/driver.py
  Face-Detection/Face detection using probabilistic-modelling/Adaboost/haar_features.py
  Face-Detection/Face detection using probabilistic-modelling/README.md
  Face-Detection/Face detection using probabilistic-modelling/dataset_preparation.py
  Face-Detection/Face detection using probabilistic-modelling/driver.py
  Face-Detection/Face detection using probabilistic-modelling/factor_analyzer.py
  Face-Detection/Face detection using probabilistic-modelling/gaussian.py
  Face-Detection/Face detection using probabilistic-modelling/t_distribution.py
  Face-Detection/Face detection using probabilistic-modelling/t_mixture.py
  Face-Mask-Detection/Face-detection-using-PCA/PCA Mini-Project.ipynb
  Face-Mask-Detection/Face-detection-using-PCA/README.md
  Face-Mask-Detection/Face-detection-using-PCA/pca.png
  Face-Mask-Detection/Face-detection-using-PCA/result.png
Labels: Level3, gssoc21

#882 World No Tobacco Day Filter #879
  Snapchat_Filters/Festive-Filter/World No Tobacco Day Filter/Code.py
  Snapchat_Filters/Festive-Filter/World No Tobacco Day Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filter/World No Tobacco Day Filter/Images/Tobacco.png
  Snapchat_Filters/Festive-Filter/World No Tobacco Day Filter/Images/World No Tobacco Day Filtered Image.png
  Snapchat_Filters/Festive-Filter/World No Tobacco Day Filter/README.md
Labels: Level3, gssoc21

#881 World No Alcohol Day Filter #878
  Snapchat_Filters/Festive-Filter/World No Alcohol Day Filter/Code.py
  Snapchat_Filters/Festive-Filter/World No Alcohol Day Filter/Images_/Alcohol.png
  Snapchat_Filters/Festive-Filter/World No Alcohol Day Filter/Images_/Image.jpg
  Snapchat_Filters/Festive-Filter/World No Alcohol Day Filter/Images_/World No Alcohol Day Filtered Image.png
  Snapchat_Filters/Festive-Filter/World No Alcohol Day Filter/README.md
Labels: Level3, gssoc21

#874 World Yoga Day Filter #866
  Snapchat_Filters/Festive-Filter/World Yoga Day Filter/Code.py
  Snapchat_Filters/Festive-Filter/World Yoga Day Filter/Images___/Image.jpg
  Snapchat_Filters/Festive-Filter/World Yoga Day Filter/Images___/World Yoga Day Filtered Image.png .PNG
  Snapchat_Filters/Festive-Filter/World Yoga Day Filter/Images___/Yoga.png
  Snapchat_Filters/Festive-Filter/World Yoga Day Filter/README.md
Labels: Level3, gssoc21

#860 Window Filter
  Snapchat_Filters/WindowFilter/README.md
  Snapchat_Filters/WindowFilter/WINDOW.png
  Snapchat_Filters/WindowFilter/requirements.txt
  Snapchat_Filters/WindowFilter/win.py
Labels: Level3, gssoc21

#854 Big eyebrows and Red Glasses Filter
  Snapchat_Filters/Big eyebrows and Red Glasses Filter/Code.py
  Snapchat_Filters/Big eyebrows and Red Glasses Filter/Images/Big Eyebrows and Red Glass Filtered Image.png
  Snapchat_Filters/Big eyebrows and Red Glasses Filter/Images/Image.jpg
  Snapchat_Filters/Big eyebrows and Red Glasses Filter/Images/Red Glass.png
  Snapchat_Filters/Big eyebrows and Red Glasses Filter/README.md
Labels: Level3, gssoc21

#820 eyes lens color change
  Virtual_makeover/eye_lens/README.md
  Virtual_makeover/eye_lens/eye_lens.py
  Virtual_makeover/eye_lens/image1.png
  Virtual_makeover/eye_lens/outputs/Screenshot (607).png
  Virtual_makeover/eye_lens/outputs/mask(colored).png
  Virtual_makeover/eye_lens/outputs/mask.png
  Virtual_makeover/eye_lens/outputs/output1.png
  Virtual_makeover/eye_lens/outputs/output3.png
Labels: Level3, gssoc21

#834 Polaroid fiter
  Snapchat_Filters/PolaroidFilter/README.md
  Snapchat_Filters/PolaroidFilter/pol.png
  Snapchat_Filters/PolaroidFilter/pol.py
  Snapchat_Filters/PolaroidFilter/requirements.txt
Labels: Level3, gssoc21

#872 added birthday cap
  Snapchat_Filters/birthday_filter/Birthday.py
  Snapchat_Filters/birthday_filter/README.md
  Snapchat_Filters/birthday_filter/face.xml
  Snapchat_Filters/birthday_filter/pic1.png
  Snapchat_Filters/birthday_filter/pic2.png
  Snapchat_Filters/birthday_filter/requirements.txt
Labels: Level3, gssoc21

#801 Kolhapuri hat added
  Snapchat_Filters/Kolhapuri_hat_filter/Kolhapuri_Filter.py
  Snapchat_Filters/Kolhapuri_hat_filter/README.md
  Snapchat_Filters/Kolhapuri_hat_filter/kolhapuri.png
  Snapchat_Filters/Kolhapuri_hat_filter/requirements.txt
Labels: Level3, gssoc21

#859 Wanted filter
  Snapchat_Filters/Wanted_filter/README.md
  Snapchat_Filters/Wanted_filter/requirements.txt
  Snapchat_Filters/Wanted_filter/wanted.png
  Snapchat_Filters/Wanted_filter/wanted.py
Labels: Level3, gssoc21

#837 BunnyEarsWhiskers Filter
  Snapchat_Filters/BunnyEarsWhiskers/README.md
  Snapchat_Filters/BunnyEarsWhiskers/bears.png
  Snapchat_Filters/BunnyEarsWhiskers/bnose.png
  Snapchat_Filters/BunnyEarsWhiskers/bunny_f.py
  Snapchat_Filters/BunnyEarsWhiskers/requirements.txt
Labels: Level3, gssoc21

#815 Navratri Festival Filter #812
  Snapchat_Filters/Festive-Filter/Navratri Festival Filter/Code.py
  Snapchat_Filters/Festive-Filter/Navratri Festival Filter/Images_/Image.jpg
  Snapchat_Filters/Festive-Filter/Navratri Festival Filter/Images_/Navratri Festival Filtered Image.png
  Snapchat_Filters/Festive-Filter/Navratri Festival Filter/Images_/Navratri.png
  Snapchat_Filters/Festive-Filter/Navratri Festival Filter/README.md
Labels: Level3, gssoc21

#799 Wolverine Filter added
  Snapchat_Filters/Wolverine_Filter/README.md
  Snapchat_Filters/Wolverine_Filter/Wolverine_Filter.py
  Snapchat_Filters/Wolverine_Filter/requirements.txt
  Snapchat_Filters/Wolverine_Filter/wolvie.png
Labels: Level3, gssoc21

#798 Batman Filter Added
  Snapchat_Filters/Batman_Filter/Batman_Filter.py
  Snapchat_Filters/Batman_Filter/README.md
  Snapchat_Filters/Batman_Filter/bat.png
  Snapchat_Filters/Batman_Filter/requirements.txt
Labels: Level3, gssoc21

#793 Muharram Festival Filter #785
  Snapchat_Filters/Festive-Filter/Muharram Festival Filter/Code.py
  Snapchat_Filters/Festive-Filter/Muharram Festival Filter/Images/Image.jpg
  Snapchat_Filters/Festive-Filter/Muharram Festival Filter/Images/Muharram Festival Filtered Image.png
  Snapchat_Filters/Festive-Filter/Muharram Festival Filter/Images/Muharram.png
  Snapchat_Filters/Festive-Filter/Muharram Festival Filter/README.md
Labels: Level3, gssoc21

#788 New Year Filter #781
  Snapchat_Filters/Festive-Filter/New Year/Code.py
  Snapchat_Filters/Festive-Filter/New Year/Images_/Image.jpg
  Snapchat_Filters/Festive-Filter/New Year/Images_/New Year Filtered Image.png
  Snapchat_Filters/Festive-Filter/New Year/Images_/New Year.png
  Snapchat_Filters/Festive-Filter/New Year/README.md
Labels: Level3, gssoc21

#902 Create Readme.md for image pyramiding
  Awesome-face-operations/face-pyramiding/Readme.md
Labels: LGM-SOC 21, 🟨 Level : 2

#900 Fixed Issue #796
  CONTRIBUTORS.md
  Snapchat_Filters/Rainbow_filter/Rainbow_filter.py
  Snapchat_Filters/Rainbow_filter/haarcascade_mcs_mouth.xml/haarcascade_mcs_mouth.xml
Labels: LGM-SOC 21, 🟩 Level : 1

#901 Added javascript face-detection
  Face-Detection/Face-Detection-using-Chrome-API/README.md
  Face-Detection/Face-Detection-using-Chrome-API/css/style.css
  Face-Detection/Face-Detection-using-Chrome-API/index.html
  Face-Detection/Face-Detection-using-Chrome-API/js/face-detection.js
  Face-Detection/Face-Detection-using-Chrome-API/js/index.js
Labels: LGM-SOC 21, 🟧 Level : 3
