Repository akshitagupta15june/Face-X, pull requests merged in 2021-01, with the labels that each got.

#86 Snapchat Filter
  Snapchat_Filters/Joker with Cartoon Effect/Hat.jpg
  Snapchat_Filters/Joker with Cartoon Effect/Joker.py
  Snapchat_Filters/Joker with Cartoon Effect/Lips.jpg
  Snapchat_Filters/Joker with Cartoon Effect/Nose.jpg
  Snapchat_Filters/Joker with Cartoon Effect/Output_image.png
  Snapchat_Filters/Joker with Cartoon Effect/README.md
Labels: Medium, SWoC 2021

#119 Added facial biometric detecter
  Facial_Biometric/Capture.jpg
  Facial_Biometric/Capture2.jpg
  Facial_Biometric/Readme.md
  Facial_Biometric/library.py
Labels: SWoC 2021, SwoC30

#122 Added Snapchat filter - SantaClaus filter
  Snapchat_Filters/SantaClaus Filter/README.md
  Snapchat_Filters/SantaClaus Filter/assets/out.png
  Snapchat_Filters/SantaClaus Filter/assets/santa_beard.png
  Snapchat_Filters/SantaClaus Filter/assets/santa_hat.png
  Snapchat_Filters/SantaClaus Filter/santa_filter.py
Labels: SWoC 2021, SwoC30

#138 Adding Readme to lBPH and CNN algorithm #128
  .idea/Face-X.iml
  .idea/encodings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  .vscode/launch.json
  Recognition-Algorithms/Facial Recognition using LBPH/Readme.md
  Recognition-Algorithms/Facial Recognition using LBPH/images/fork.png
  Recognition-Algorithms/Facial Recognition using LBPH/images/pic1.png
  Recognition-Algorithms/Facial Recognition using LBPH/images/pic2.png
  Recognition-Algorithms/Facial Recognition using LBPH/images/pic3.png
  Recognition-Algorithms/Recognition Using Cnn/Images/Screenshot from 2020-12-11 17-59-00.png
  Recognition-Algorithms/Recognition Using Cnn/Images/Screenshot from 2020-12-11 21-34-18.png
  Recognition-Algorithms/Recognition Using Cnn/Readme.md
Labels: JWOC, easy

#135 Added Dog filter
  Snapchat_Filters/Dog_filter/README.md
  Snapchat_Filters/Dog_filter/requirements.txt
  Snapchat_Filters/Dog_filter/src/assets/0_28809.png
  Snapchat_Filters/Dog_filter/src/assets/1_25803.png
  Snapchat_Filters/Dog_filter/src/assets/2_1028.png
  Snapchat_Filters/Dog_filter/src/assets/child.png
  Snapchat_Filters/Dog_filter/src/assets/children.png
  Snapchat_Filters/Dog_filter/src/assets/dalmation.png
  Snapchat_Filters/Dog_filter/src/assets/dog.png
  Snapchat_Filters/Dog_filter/src/assets/example.png
  Snapchat_Filters/Dog_filter/src/assets/example_adversarial_r.npy
  Snapchat_Filters/Dog_filter/src/assets/haarcascade_frontalface_default.xml
  Snapchat_Filters/Dog_filter/src/assets/model_best.pth
  Snapchat_Filters/Dog_filter/src/assets/sheepdog.png
  Snapchat_Filters/Dog_filter/src/data/data.py
  Snapchat_Filters/Dog_filter/src/outputs/child_with_cat_mask.png
  Snapchat_Filters/Dog_filter/src/outputs/child_with_dalmation_mask.png
  Snapchat_Filters/Dog_filter/src/outputs/child_with_dog_mask.png
  Snapchat_Filters/Dog_filter/src/outputs/children_detected.png
  Snapchat_Filters/Dog_filter/src/outputs/diamond.png
  Snapchat_Filters/Dog_filter/src/outputs/example_adversarial.png
  Snapchat_Filters/Dog_filter/src/outputs/example_adversarial_r.npy
  Snapchat_Filters/Dog_filter/src/outputs/perf_feat_ols.png
  Snapchat_Filters/Dog_filter/src/outputs/perf_feat_ridge_ols.png
  Snapchat_Filters/Dog_filter/src/outputs/pokeball.png
  Snapchat_Filters/Dog_filter/src/outputs/resized_dog.jpg
  Snapchat_Filters/Dog_filter/src/outputs/results.txt
  Snapchat_Filters/Dog_filter/src/step_2_face_detect.py
  Snapchat_Filters/Dog_filter/src/step_3_camera_face_detect.py
  Snapchat_Filters/Dog_filter/src/step_3_camera_test.py
  Snapchat_Filters/Dog_filter/src/step_4_dog_mask.py
  Snapchat_Filters/Dog_filter/src/step_4_dog_mask_simple.py
  Snapchat_Filters/Dog_filter/src/step_4_generate_image_from_array.py
  Snapchat_Filters/Dog_filter/src/step_5_ls_simple.py
  Snapchat_Filters/Dog_filter/src/step_6_ls.py
  Snapchat_Filters/Dog_filter/src/step_6_ls_simple.py
  Snapchat_Filters/Dog_filter/src/step_6_plot.py
  Snapchat_Filters/Dog_filter/src/step_7_fer.py
  Snapchat_Filters/Dog_filter/src/step_7_fer_eval.py
  Snapchat_Filters/Dog_filter/src/step_7_fer_simple.py
  Snapchat_Filters/Dog_filter/src/step_8_dog_emotion_mask.py
  Snapchat_Filters/Dog_filter/src/step_9_adversarial_example.py
Labels: JWOC, Medium

#141 Resolved issue #78
  Recognition-Algorithms/README.md
Labels: JWOC, Medium

#146 Adding Thug life filter.
  Snapchat_Filters/ThugLife/Smoke weed everyday.mp3
  Snapchat_Filters/ThugLife/capture.jpg
  Snapchat_Filters/ThugLife/cigar.png
  Snapchat_Filters/ThugLife/glass.png
  Snapchat_Filters/ThugLife/haarcascade_frontalface_default.xml
  Snapchat_Filters/ThugLife/readme.md
  Snapchat_Filters/ThugLife/thug_life.py
Labels: JWOC, Medium

#143 Added virtual makeover
  Virtual_makeover/makeup/Emma-watson_main_character_pic.jpg
  Virtual_makeover/makeup/README.md
  Virtual_makeover/makeup/digital_makeup.py
  Virtual_makeover/makeup/makeover.png
Labels: CHAGES-REQUESTED, JWOC

#148 Uploaded the ensemble facial recognition
  Recognition-Algorithms/Ensemble_facial_recognition/Database/mark1.jpg
  Recognition-Algorithms/Ensemble_facial_recognition/Database/mark2.jpg
  Recognition-Algorithms/Ensemble_facial_recognition/Database/mark3.jpg
  Recognition-Algorithms/Ensemble_facial_recognition/Database/mark4.jfif
  Recognition-Algorithms/Ensemble_facial_recognition/Database/mark5.jfif
  Recognition-Algorithms/Ensemble_facial_recognition/Database/representations_ensemble.pkl
  Recognition-Algorithms/Ensemble_facial_recognition/Dataset/steve1.jpg
  Recognition-Algorithms/Ensemble_facial_recognition/Dataset/steve2.jfif
  Recognition-Algorithms/Ensemble_facial_recognition/Dataset/steve3.jpg
  Recognition-Algorithms/Ensemble_facial_recognition/README.md
  Recognition-Algorithms/Ensemble_facial_recognition/program.ipynb
Labels: CHAGES-REQUESTED, SWoC 2021

#158 Added EfficientNetB1
  Recognition-Algorithms/Recognition using Efficient Net B1/EfficientNetB1.ipynb
  Recognition-Algorithms/Recognition using Efficient Net B1/README.md
  Recognition-Algorithms/Recognition using Efficient Net B1/accuracy.png
  Recognition-Algorithms/Recognition using Efficient Net B1/heatmap.png
Labels: DWOC, Level-4
