Repository akshitagupta15june/Face-X, pull requests merged in 2021-04, with the labels that each got.

#439 [FaceX Library]Adding more OpenCV algorithms
  facex-library/README.md
  facex-library/__pycache__/facex.cpython-36.pyc
  facex-library/demo.py
  facex-library/facex.py
  facex/README.md
  facex/__pycache__/facex.cpython-36.pyc
  facex/demo.py
  facex/facex.py
  facex/facex/Blurring image across face/.idea/.gitignore
  facex/facex/Blurring image across face/.idea/inspectionProfiles/Project_Default.xml
  facex/facex/Blurring image across face/.idea/inspectionProfiles/profiles_settings.xml
  facex/facex/Blurring image across face/.idea/misc.xml
  facex/facex/Blurring image across face/.idea/modules.xml
  facex/facex/Blurring image across face/.idea/other.xml
  facex/facex/Blurring image across face/.idea/pythonProject.iml
  facex/facex/Blurring image across face/haarcascade_frontalface_default.xml
  facex/facex/Blurring image across face/main.py
  facex/facex/Blurring image across face/output.png
  facex/facex/Cartoonify/Cartoonification/Cartoonified_image.jpg
  facex/facex/Cartoonify/Cartoonification/Readme.md
  facex/facex/Cartoonify/Cartoonification/cartoonify_without_GUI.py
  facex/facex/Cartoonify/Cartoonification/cwoc.jpeg
  facex/facex/Cartoonify/Cartoonification/dicaprio.jpg
  facex/facex/Cartoonify/Cartoonification/gssoc.png
  facex/facex/Cartoonify/Cartoonification/uaceit.jpeg
  facex/facex/Cartoonify/Cartoonify-GUI/GUI.png
  facex/facex/Cartoonify/Cartoonify-GUI/Readme.md
  facex/facex/Cartoonify/Cartoonify-GUI/cartoonified.jpg
  facex/facex/Cartoonify/Cartoonify-GUI/cartoonify-gui.py
  facex/facex/Cartoonify/Cartoonify-GUI/dicaprio.jpg
  facex/facex/Cartoonify/Cartoonify-GUI/mq2.jpg
  facex/facex/Cartoonify/Cartoonify-GUI/wp2030093.jpg
  facex/facex/Cartoonify/Cartoonify_face_image/Cartoonify-face_image.py
  facex/facex/Cartoonify/Cartoonify_face_image/Carttonified.jpg
  facex/facex/Cartoonify/Cartoonify_face_image/Images/after_face.png
  facex/facex/Cartoonify/Cartoonify_face_image/Images/face.jpg
  facex/facex/Cartoonify/Cartoonify_face_image/Images/readme.md
  facex/facex/Cartoonify/Cartoonify_face_image/readme.md
  facex/facex/Cartoonify/facex.jpeg
  facex/facex/Cartoonify/logo/Face-X.png
  facex/facex/Cartoonify/logo/FaceX.svg
  facex/facex/Face_Detection_using_OpenCV/Face_detection.py
  facex/facex/Face_Detection_using_OpenCV/haarcascade_frontalface_default.xml
  facex/facex/Face_Detection_using_OpenCV/video_face_detect_opencv.py
Labels: Level3, gssoc21

#440 Improve the readme.md
  Awesome-face-operations/Face-Morphing/readme.md
Labels: Level1, gssoc21

#441 Updated Snapchat Filter Readme.md
  Snapchat_Filters/Readme.md
Labels: Level1, gssoc21

#444 Colorful Sketch Filter
  Awesome-face-operations/Colorful Sketch Filter/Images/Colorful Sketch Filtered Photo.jpg
  Awesome-face-operations/Colorful Sketch Filter/Images/Photo.jpg
  Awesome-face-operations/Colorful Sketch Filter/README.md
  Awesome-face-operations/Colorful Sketch Filter/colorful_sketch_filter.py
Labels: Level3, gssoc21

#450 Updated Cartoonification Readme File
  Cartoonify Image/Cartoonification/Assets/Threshold.jpg
  Cartoonify Image/Cartoonification/Assets/Title .png
  Cartoonify Image/Cartoonification/Assets/abe_toon.png
  Cartoonify Image/Cartoonification/Assets/boy.png
  Cartoonify Image/Cartoonification/Assets/cwoc.jpeg
  Cartoonify Image/Cartoonification/Assets/edge.png
  Cartoonify Image/Cartoonification/Assets/filters_tutorial_02.png
  Cartoonify Image/Cartoonification/Assets/gssoc.png
  Cartoonify Image/Cartoonification/Assets/preview-removebg.png
  Cartoonify Image/Cartoonification/Assets/result (2).jpg
  Cartoonify Image/Cartoonification/Assets/uaceit.jpeg
  Cartoonify Image/Cartoonification/Assets/vishal.txt
  Cartoonify Image/Cartoonification/Cartoonified_image.jpg
  Cartoonify Image/Cartoonification/Readme.md
  Cartoonify Image/Cartoonification/dicaprio.jpg
Labels: Level2, gssoc21

#453 Updated Readme broken links in FaceMask Detection.
  Face-Mask-Detection/Readme.md
Labels: Level0, gssoc21

#455 Added background remover
  Awesome-face-operations/Video-BG-Substraction/Background Substraction.py
  Awesome-face-operations/Video-BG-Substraction/readme.md
Labels: Level3, gssoc21

#454 Gender detection
  Awesome-face-operations/Gender_Classification/Gender_final.h5
  Awesome-face-operations/Gender_Classification/Readme.md
  Awesome-face-operations/Gender_Classification/Test_model.ipynb
  Awesome-face-operations/Gender_Classification/gender-implementation.ipynb
  Awesome-face-operations/Gender_Classification/haarcascade_frontalface_default.xml
  Awesome-face-operations/Gender_Classification/test_data/249310.png
  Awesome-face-operations/Gender_Classification/test_data/35_years_old.png
  Awesome-face-operations/Gender_Classification/test_data/4c.jpg
  Awesome-face-operations/Gender_Classification/test_data/close.jpg
  Awesome-face-operations/Gender_Classification/test_data/dec.jpg
  Awesome-face-operations/Gender_Classification/test_data/fee.jpg
  Awesome-face-operations/Gender_Classification/test_data/man.jpg
Labels: Level3, gssoc21

#458 Added template detection
  Awesome-face-operations/Template-Detection/Template-Detection.py
  Awesome-face-operations/Template-Detection/images.jpg
  Awesome-face-operations/Template-Detection/readme.md
Labels: Level3, gssoc21

#462 Multiple template added
  Awesome-face-operations/Multiple-Template-Matching/Multiple_Template_Matching.py
  Awesome-face-operations/Multiple-Template-Matching/readme.md
  Awesome-face-operations/Multiple-Template-Matching/res_mario.jpg
Labels: Level3, gssoc21

#475 Neural Style Transfer
  Awesome-face-operations/Style-Transfer/.gitignore
  Awesome-face-operations/Style-Transfer/README.md
  Awesome-face-operations/Style-Transfer/exp1/blonde.jpg
  Awesome-face-operations/Style-Transfer/exp1/delaunay.jpg
  Awesome-face-operations/Style-Transfer/exp1/final_image.png
  Awesome-face-operations/Style-Transfer/style_transfer.ipynb
Labels: Level3, gssoc21

#476 Goggles changing Filter added
  Snapchat_Filters/Goggles_Changing_Filter/Goggle_filter.py
  Snapchat_Filters/Goggles_Changing_Filter/README.md
  Snapchat_Filters/Goggles_Changing_Filter/assets/glasses.png
  Snapchat_Filters/Goggles_Changing_Filter/assets/moustache.png
  Snapchat_Filters/Goggles_Changing_Filter/assets/sun_1.png
  Snapchat_Filters/Goggles_Changing_Filter/requirements.txt
Labels: Level3, gssoc21

#477 Update Readme Mosaic Effect
  Awesome-face-operations/Mosaic-Effect/Mosaic-Images/Mosaic3.png
  Awesome-face-operations/Mosaic-Effect/Mosaic-Images/hqdefault.jpg
  Awesome-face-operations/Mosaic-Effect/Mosaic-Images/images1.png
  Awesome-face-operations/Mosaic-Effect/Mosaic-Images/mark-zuckerberg.jpg
  Awesome-face-operations/Mosaic-Effect/Mosaic-Images/mosaic.png
  Awesome-face-operations/Mosaic-Effect/Mosaic-Images/named.jpg
  Awesome-face-operations/Mosaic-Effect/Mosaic-Images/pyramid.png
  Awesome-face-operations/Mosaic-Effect/images (1).jpg
  Awesome-face-operations/Mosaic-Effect/images.jpg
  Awesome-face-operations/Mosaic-Effect/readme.md
Labels: Level2, gssoc21

#478 Vgg16 - Face Recognition
  Recognition-Algorithms/Face Recognition using VGG/Fine_Tuning Model.ipynb
  Recognition-Algorithms/Face Recognition using VGG/Load_Test_Files.ipynb
  Recognition-Algorithms/Face Recognition using VGG/README.md
  Recognition-Algorithms/Face Recognition using VGG/Training VGG Model.ipynb
  Recognition-Algorithms/Face Recognition using VGG/assets/Dataset.PNG
  Recognition-Algorithms/Face Recognition using VGG/assets/Dataset_twist.PNG
  Recognition-Algorithms/Face Recognition using VGG/assets/cf.jpg
  Recognition-Algorithms/Face Recognition using VGG/assets/mg.jpg
  Recognition-Algorithms/Face Recognition using VGG/assets/mgresult.PNG
  Recognition-Algorithms/Face Recognition using VGG/assets/name.PNG
  Recognition-Algorithms/Face Recognition using VGG/haarcascade_frontalface_default.xml
Labels: Level3, gssoc21

#481 Update Readme.md
  Face-Mask-Detection/Readme.md
Labels: Level3, gssoc21

#486 Glitter Filter
  Awesome-face-operations/Glitter Filter/Images/(Glitter Filtered)Photo.jpg
  Awesome-face-operations/Glitter Filter/Images/Photo.jpg
  Awesome-face-operations/Glitter Filter/README.md
  Awesome-face-operations/Glitter Filter/glitter filter.py
Labels: Level3, gssoc21

#489 Added new snap-chat filter
  Snapchat_Filters/mustache and black sunglasses/README.md
  Snapchat_Filters/mustache and black sunglasses/Snapchat_Filter.ipynb
Labels: Level3, gssoc21

#488 Add Recognition using DWT algorithm
  Recognition-Algorithms/Recognition using DWT algorithm/Dwt.py
  Recognition-Algorithms/Recognition using DWT algorithm/Images/1-Figure.png
  Recognition-Algorithms/Recognition using DWT algorithm/Images/C.png
  Recognition-Algorithms/Recognition using DWT algorithm/Images/Gorup1.png
  Recognition-Algorithms/Recognition using DWT algorithm/Images/dwt.png
  Recognition-Algorithms/Recognition using DWT algorithm/Images/hqdefault .jpg
  Recognition-Algorithms/Recognition using DWT algorithm/Images/lena2.png
  Recognition-Algorithms/Recognition using DWT algorithm/Images/oj.png
  Recognition-Algorithms/Recognition using DWT algorithm/Readme.md
Labels: Level3, gssoc21

#448 facial recognition attendance marking system in openCV
  Face-Detection/face-detection-attendance-system-using-OpenCV
Labels: Level3, gssoc21

#317 Added xception model for face recognition
  Recognition-Algorithms/Recognition_using_Xception/create_dataset.py
  Recognition-Algorithms/Recognition_using_Xception/main.py
  Recognition-Algorithms/Recognition_using_Xception/models/__init__.py
  Recognition-Algorithms/Recognition_using_Xception/models/xception.py
  Recognition-Algorithms/Recognition_using_Xception/output.py
  Recognition-Algorithms/Recognition_using_Xception/readme.md
  Recognition-Algorithms/Recognition_using_Xception/requirements.txt
Labels: Level3, gssoc21

#498 Bunny Nose issue no.: #386
  Snapchat_Filters/Bunny_Nose/Bunny_Nose_Filter.py
  Snapchat_Filters/Bunny_Nose/bunny.png
Labels: Level3, gssoc21

#501 Added Implementation for EfficientNetB3
  Face-Mask-Detection/Recognition using EfficientNetB3/Face Mask detector.ipynb
  Face-Mask-Detection/Recognition using EfficientNetB3/Mask.png
  Face-Mask-Detection/Recognition using EfficientNetB3/README.md
  Face-Mask-Detection/Recognition using EfficientNetB3/face mask detection- mtcnn.png
  Face-Mask-Detection/Recognition using EfficientNetB3/face_detector.py
Labels: Level3, gssoc21

#499 Modify face-mask-detection-using-cnn #432
  Face-Mask-Detection/face-mask-detection-using-cnn/Modify_face_mask_detection_using_cnn_ (1).ipynb
Labels: Level1, gssoc21

#508 Add Readme Bunny-Nose Filter
  Snapchat_Filters/Bunny_Nose/Images/Bunny-nose3.png
  Snapchat_Filters/Bunny_Nose/Images/Bunny-nose4.png
  Snapchat_Filters/Bunny_Nose/Images/Bunny-nose5.png
  Snapchat_Filters/Bunny_Nose/Images/Bunny.png
  Snapchat_Filters/Bunny_Nose/Images/eyeflow.png
  Snapchat_Filters/Bunny_Nose/Images/face-landmark.png
  Snapchat_Filters/Bunny_Nose/Images/result.jpg
  Snapchat_Filters/Bunny_Nose/Readme.md
Labels: Level2, gssoc21

#511 GANs Face Completion / Issue 429
  Awesome-face-operations/GANS_Face_Completion/README.md
  Awesome-face-operations/GANS_Face_Completion/model.py
  Awesome-face-operations/GANS_Face_Completion/result/result_100.png
  Awesome-face-operations/GANS_Face_Completion/result/result_199.png
  Awesome-face-operations/GANS_Face_Completion/result/result_50.png
  Awesome-face-operations/GANS_Face_Completion/result/result_test_0.png
  Awesome-face-operations/GANS_Face_Completion/test.py
  Awesome-face-operations/GANS_Face_Completion/test/1.jpg
  Awesome-face-operations/GANS_Face_Completion/test/2.jpg
  Awesome-face-operations/GANS_Face_Completion/test/3.jpg
  Awesome-face-operations/GANS_Face_Completion/test/4.jpg
  Awesome-face-operations/GANS_Face_Completion/train.py
  Awesome-face-operations/GANS_Face_Completion/utils.py
Labels: Level3, gssoc21

#509 Readme Updated for Awesome-Face-Operation
  Awesome-face-operations/Readme.md
Labels: Level2, gssoc21

#513 Update Readme File Recognition-using-IOT
  Recognition-using-IOT/Images/ARDUINO.png
  Recognition-using-IOT/Images/Arc.png
  Recognition-using-IOT/Images/IOT-banner2.png
  Recognition-using-IOT/Images/Iot.jpg
  Recognition-using-IOT/Images/Iot1.png
  Recognition-using-IOT/Images/MacV.png
  Recognition-using-IOT/Images/MachineVision.png
  Recognition-using-IOT/Images/Untitled1.png
  Recognition-using-IOT/Images/aws-header.png
  Recognition-using-IOT/Images/machinedesign1.png
  Recognition-using-IOT/readme.md
Labels: Level1, gssoc21

#517 Oil Paint Filter
  Awesome-face-operations/Oil Paint Filter/Images/(Oil Paint Filtered)Photo.jpg
  Awesome-face-operations/Oil Paint Filter/Images/Photo.jpg
  Awesome-face-operations/Oil Paint Filter/README.md
  Awesome-face-operations/Oil Paint Filter/oil paint.py
Labels: Level3, gssoc21

#524 Added Readme.md file in Awesome-face-operations/Face Deblurring
  Awesome-face-operations/Face Deblurring/Readme.md
Labels: Level2, gssoc21

#523 Updated Readme For Xception Algorithm
  Recognition-Algorithms/Recognition_using_Xception/Convolution_of_box_signal_with_itself.gif
  Recognition-Algorithms/Recognition_using_Xception/readme.md
Labels: Level2, gssoc21

#521 Recognition using orb algorithm
  Recognition-Algorithms/Recognition Using ORB/ORB_Algorithm.py
  Recognition-Algorithms/Recognition Using ORB/Readme.md
Labels: Level3, gssoc21

#520 Adding feature: IRIS Recognition
  Awesome-face-operations/IRIS Recognition
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/FeatureExtraction.py
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/ImageEnhancement.py
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/Images/Fig1.png
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/Images/Fig2.png
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/Images/Fig3.png
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/Images/Fig4.png
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/Images/Fig5.png
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/Images/Fig6.png
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/Images/Fig7.png
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/Images/Fig8.png
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/Images/code1.png
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/Images/code2.png
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/Images/code3.png
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/IrisLocalization.py
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/IrisMatching.py
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/IrisNormalization.py
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/IrisRecognition.py
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/PerformanceEvaluation.py
  Awesome-face-operations/Iris-Recognition-master/Iris-Recognition-master/README.md
Labels: Level3, gssoc21

#527 updated Face Recognition Using Inception V3 model
  Recognition-Algorithms/Face Recognition Using Inception V3 model/Images/10-png.png
  Recognition-Algorithms/Face Recognition Using Inception V3 model/Images/Unt1.png
  Recognition-Algorithms/Face Recognition Using Inception V3 model/Images/community.png
  Recognition-Algorithms/Face Recognition Using Inception V3 model/Images/facial.png
  Recognition-Algorithms/Face Recognition Using Inception V3 model/Images/inceptionv3.png
  Recognition-Algorithms/Face Recognition Using Inception V3 model/Images/pas.png
  Recognition-Algorithms/Face Recognition Using Inception V3 model/Images/pasted.png
  Recognition-Algorithms/Face Recognition Using Inception V3 model/Images/remotesensing.png
  Recognition-Algorithms/Face Recognition Using Inception V3 model/Inception.py
  Recognition-Algorithms/Face Recognition Using Inception V3 model/Readme.md
Labels: Level3, gssoc21

#529 Added Face Recognition using Face-net
  Recognition-Algorithms/Face Recognition using FaceNet/README.md
  Recognition-Algorithms/Face Recognition using FaceNet/data/arrays/embeddings.npz
  Recognition-Algorithms/Face Recognition using FaceNet/data/arrays/vars.npz
  Recognition-Algorithms/Face Recognition using FaceNet/data/cascade/haarcascade_frontalface_default.xml
  Recognition-Algorithms/Face Recognition using FaceNet/data/faces/Chris Hemsworth.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/faces/Hugh Jackman.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/faces/Ian Somerhalder.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/faces/Jeremy Renner.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/faces/Joseph Morgan.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/faces/Kit Harington.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/faces/Mark Ruffalo.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/faces/Nathaniel Buzolic.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/faces/Robert Downey Jr..jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/faces/Scarlett Johansson .jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/faces/Tom Holland.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/font/Calibri Regular.ttf
  Recognition-Algorithms/Face Recognition using FaceNet/data/images/Chris Hemsworth.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/images/Hugh Jackman.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/images/Ian Somerhalder.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/images/Jeremy Renner.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/images/Joseph Morgan.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/images/Kit Harington.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/images/Mark Ruffalo.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/images/Nathaniel Buzolic.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/images/Robert Downey Jr..jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/images/Scarlett Johansson .jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/images/Tom Holland.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/data/model/dummy file.txt
  Recognition-Algorithms/Face Recognition using FaceNet/image_recognition.py
  Recognition-Algorithms/Face Recognition using FaceNet/live_recognition.py
  Recognition-Algorithms/Face Recognition using FaceNet/requirements.txt
  Recognition-Algorithms/Face Recognition using FaceNet/script/detect_faces.py
  Recognition-Algorithms/Face Recognition using FaceNet/script/fx.py
  Recognition-Algorithms/Face Recognition using FaceNet/script/generate_data.py
  Recognition-Algorithms/Face Recognition using FaceNet/test/00000PORTRAIT_00000_BURST20180310144236486.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/test/2ec945ecd5f7c08789f3ef5da5287410.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/test/3840x2160-avengers-cast-photocall-moscow-05.JPG
  Recognition-Algorithms/Face Recognition using FaceNet/test/predicted/00000PORTRAIT_00000_BURST20180310144236486.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/test/predicted/2ec945ecd5f7c08789f3ef5da5287410.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/test/predicted/3840x2160-avengers-cast-photocall-moscow-05.JPG
  Recognition-Algorithms/Face Recognition using FaceNet/test/predicted/the-avengers-walt03.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/test/predicted/vampire-diaries.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/test/the-avengers-walt03.jpg
  Recognition-Algorithms/Face Recognition using FaceNet/test/vampire-diaries.jpg
Labels: Level3, gssoc21

#534 Documentation improvement
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Level0, gssoc21

#535 Added YoloV3 Detection
  Face-Detection/Face Detection using YoloV3/README.md
  Face-Detection/Face Detection using YoloV3/assets/outside_000001_yoloface.jpg
  Face-Detection/Face Detection using YoloV3/assets/yolo-architecture.png
  Face-Detection/Face Detection using YoloV3/cfg/face.names
  Face-Detection/Face Detection using YoloV3/cfg/face_classes.txt
  Face-Detection/Face Detection using YoloV3/cfg/yolo_anchors.txt
  Face-Detection/Face Detection using YoloV3/cfg/yolov3-face.cfg
  Face-Detection/Face Detection using YoloV3/model-weights/get_models.sh
  Face-Detection/Face Detection using YoloV3/requirements.txt
  Face-Detection/Face Detection using YoloV3/samples/meeting_11_304.jpg
  Face-Detection/Face Detection using YoloV3/samples/outside_000001.jpg
  Face-Detection/Face Detection using YoloV3/scripts/run_yolo_face_image.sh
  Face-Detection/Face Detection using YoloV3/yolo/model.py
  Face-Detection/Face Detection using YoloV3/yolo/yolo.py
  Face-Detection/Face Detection using YoloV3/yoloface.py
Labels: Level3, gssoc21

#539 Updated Main Readme File
  .github/Assests/537-5375273_teamwork-isometric-illustration-clipart-removebg-preview.png
  .github/Assests/Asome.png
  .github/Assests/Offical_logo-Face-x.png
  .github/Assests/Untitled (2).png
  .github/Assests/face-mask-logo-template_23-2148746217__3_-removebg-preview.png
  .github/Assests/hand.png
  .github/Assests/isometric.png
  .github/Assests/kis-r.png
  .github/Assests/logo.png
  .github/Assests/qww.png
  .github/Assests/sp_logo.png
  .github/Assests/vishal.png
  Readme.md
Labels: Level2, gssoc21

#544 Updated Face recognition using ICA (Independent Component Analysis)
  Recognition-Algorithms/Face recognition using ICA (Independent Component Analysis)/ICA.py
  Recognition-Algorithms/Face recognition using ICA (Independent Component Analysis)/Images/A-basic-ICA-model-for-blind-source-separation.png
  Recognition-Algorithms/Face recognition using ICA (Independent Component Analysis)/Images/ICA-InfoMax-algorithm-Image-synthesis-model-for-architecture-I.png
  Recognition-Algorithms/Face recognition using ICA (Independent Component Analysis)/Images/ICA.PNG
  Recognition-Algorithms/Face recognition using ICA (Independent Component Analysis)/Images/ICA1.PNG
  Recognition-Algorithms/Face recognition using ICA (Independent Component Analysis)/Images/ICA2.PNG
  Recognition-Algorithms/Face recognition using ICA (Independent Component Analysis)/Images/World wide web_Isometric.png
  Recognition-Algorithms/Face recognition using ICA (Independent Component Analysis)/Images/nihms-199383-f0004.jpg
  Recognition-Algorithms/Face recognition using ICA (Independent Component Analysis)/Images/nihms-199383-f0005.jpg
  Recognition-Algorithms/Face recognition using ICA (Independent Component Analysis)/Images/nihms-199383-f0006.jpg
  Recognition-Algorithms/Face recognition using ICA (Independent Component Analysis)/Images/nihms-199383-f0009.jpg
  Recognition-Algorithms/Face recognition using ICA (Independent Component Analysis)/Images/nihms-199383-f0010.jpg
  Recognition-Algorithms/Face recognition using ICA (Independent Component Analysis)/Images/nihms-199383-f0016.jpg
  Recognition-Algorithms/Face recognition using ICA (Independent Component Analysis)/Readme.md
Labels: Level3, gssoc21

#537 Added emotion detection and music recommendation
  Face-Emotions-Recognition/Face emotion detection and music recommendation/Emotion detection and music recommedation.py
  Face-Emotions-Recognition/Face emotion detection and music recommendation/images/output.jpg
  Face-Emotions-Recognition/Face emotion detection and music recommendation/readme.md
Labels: Level3, gssoc21

#548 Added newly implemented algorithms in Comparative Study of the Algorithms
  Recognition-Algorithms/README.md
Labels: Level3, gssoc21

#549 Add Readme File Face Recognition Attendance Management system using opencv
  Facial Recognition Attendance Management System/Attendance system/Readme.md
  Facial Recognition Attendance Management System/Attendance system/images/1-s2.0-S2590005619300141-fx1.jpg
  Facial Recognition Attendance Management System/Attendance system/images/561-r.png
  Facial Recognition Attendance Management System/Attendance system/images/76d.png
  Facial Recognition Attendance Management System/Attendance system/images/932_generated.png
  Facial Recognition Attendance Management System/Attendance system/images/FRA4.PNG
  Facial Recognition Attendance Management System/Attendance system/images/Flow-chart-of-the-methodology-used-for-Face-Detection-and-Recognition.png
  Facial Recognition Attendance Management System/Attendance system/images/Flowchart-for-real-time-face-detection-and-recognition.png
  Facial Recognition Attendance Management System/Attendance system/images/crowd (1).png
  Facial Recognition Attendance Management System/Attendance system/images/deep_.png
  Facial Recognition Attendance Management System/Attendance system/images/images.jpg
Labels: Level2, gssoc21

#550 Update README.md for face detection using Harr Cascade
  Face-Detection/Face Detection using Haar Cascade/README.md
Labels: Level2, gssoc21

#555 Update README.md
  Awesome-face-operations/Style-Transfer/README.md
Labels: Level2, gssoc21

#556 Image-Registration
  Awesome-face-operations/ImageRegistration/.ipynb_checkpoints/ImageRegistration-checkpoint.ipynb
  Awesome-face-operations/ImageRegistration/ImageRegistration.ipynb
  Awesome-face-operations/ImageRegistration/README.md
  Awesome-face-operations/ImageRegistration/images/dist_img1.jpg
  Awesome-face-operations/ImageRegistration/images/distor_img.JPG
  Awesome-face-operations/ImageRegistration/images/img_reg.JPG
  Awesome-face-operations/ImageRegistration/images/match_img.JPG
  Awesome-face-operations/ImageRegistration/images/ref_img.JPG
  Awesome-face-operations/ImageRegistration/images/reference_img.jpg
  Awesome-face-operations/ImageRegistration/images/reg_img.JPG
Labels: Level3, gssoc21

#557 Updated Readme File : Gender Detection
  Awesome-face-operations/Gender_Classification/Assets/492682_1_En_10_Fig1_HTML.png
  Awesome-face-operations/Gender_Classification/Assets/Gender-classification-network-architecture.png
  Awesome-face-operations/Gender_Classification/Assets/Title-rpng.png
  Awesome-face-operations/Gender_Classification/Assets/Untitled (3).png
  Awesome-face-operations/Gender_Classification/Assets/Untitled (4).png
  Awesome-face-operations/Gender_Classification/Assets/cnn_illustration_a.png
  Awesome-face-operations/Gender_Classification/Assets/faces_gender.jpg
  Awesome-face-operations/Gender_Classification/Assets/intersex teens-01.png
  Awesome-face-operations/Gender_Classification/Assets/nltk-2.png
  Awesome-face-operations/Gender_Classification/Assets/vishal.png
  Awesome-face-operations/Gender_Classification/Readme.md
  Awesome-face-operations/Gender_Classification/test_data/249310.png
  Awesome-face-operations/Gender_Classification/test_data/35_years_old.png
  Awesome-face-operations/Gender_Classification/test_data/4c.jpg
  Awesome-face-operations/Gender_Classification/test_data/close.jpg
  Awesome-face-operations/Gender_Classification/test_data/dec.jpg
  Awesome-face-operations/Gender_Classification/test_data/fee.jpg
  Awesome-face-operations/Gender_Classification/test_data/man.jpg
Labels: Level2, gssoc21
