Repository akshitagupta15june/Face-X, pull requests merged in 2021-02, with the labels that each got.

#162 Added Recognition using PCA
  Recognition-Algorithms/Recognition using PCA/README.md
  Recognition-Algorithms/Recognition using PCA/imgs/eigVec1.png
  Recognition-Algorithms/Recognition using PCA/imgs/eigVec2.png
  Recognition-Algorithms/Recognition using PCA/imgs/img1.png
  Recognition-Algorithms/Recognition using PCA/imgs/img2.png
  Recognition-Algorithms/Recognition using PCA/main.py
Labels: JWOC, easy

#165 Added Face Reconstruction using Graph Convolution Networks
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/README.md
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/base_model.py
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/create_bin.py
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/face_segment.py
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/imgs/comparison.png
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/imgs/overall.jpg
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/lib/__init__.py
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/lib/aabb_normals.cpython-35m-x86_64-linux-gnu.so
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/lib/evoLVe_model.py
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/lib/graph.py
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/lib/light_cnn.py
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/lib/mesh_io.py
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/lib/mesh_renderer.py
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/lib/mesh_sampling.py
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/lib/search.py
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/lib/spatialsearch.cpython-35m-x86_64-linux-gnu.so
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/main.py
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/model_normal.py
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/model_resnet.py
  Face Reconstruction/3D Face Reconstruction using Graph Convolution Network/utils.py
Labels: DWOC, Level-4

#166 Uploaded logo for Face-X
  Cartoonify Image/logo/Face-X.png
  Cartoonify Image/logo/FaceX.svg
Labels: DWOC, Level-3

#187 Updation of Recognition using Eff-NetB2
  Recognition-Algorithms/Recognition using EfficientNetB2/Face regonition with EfficientNetB2.ipynb
  Recognition-Algorithms/Recognition using EfficientNetB2/README.md
Labels: JWOC, Medium

#193 Added 3D Face Reconstruction with Weakly-Supervised Learning
  Face Reconstruction/3D Face Reconstruction with Weakly-Supervised Learning/README.md
  Face Reconstruction/3D Face Reconstruction with Weakly-Supervised Learning/detect_landmarks_in_image.py
  Face Reconstruction/3D Face Reconstruction with Weakly-Supervised Learning/examples/cropped.jpg
  Face Reconstruction/3D Face Reconstruction with Weakly-Supervised Learning/examples/origin.jpg
  Face Reconstruction/3D Face Reconstruction with Weakly-Supervised Learning/examples/rendered.png
  Face Reconstruction/3D Face Reconstruction with Weakly-Supervised Learning/load_data.py
  Face Reconstruction/3D Face Reconstruction with Weakly-Supervised Learning/models/__pycache__/resnet_50.cpython-37.pyc
  Face Reconstruction/3D Face Reconstruction with Weakly-Supervised Learning/models/resnet_50.py
  Face Reconstruction/3D Face Reconstruction with Weakly-Supervised Learning/preprocess/__pycache__/mtcnn.cpython-37.pyc
  Face Reconstruction/3D Face Reconstruction with Weakly-Supervised Learning/preprocess/mtcnn.py
  Face Reconstruction/3D Face Reconstruction with Weakly-Supervised Learning/preprocess/utils/__pycache__/detect_face.cpython-37.pyc
  Face Reconstruction/3D Face Reconstruction with Weakly-Supervised Learning/preprocess/utils/detect_face.py
  Face Reconstruction/3D Face Reconstruction with Weakly-Supervised Learning/recon_demo.py
  Face Reconstruction/3D Face Reconstruction with Weakly-Supervised Learning/reconstruction_mesh.py
  Face Reconstruction/3D Face Reconstruction with Weakly-Supervised Learning/requirements.txt
  Face Reconstruction/3D Face Reconstruction with Weakly-Supervised Learning/utils.py
Labels: DWOC, Level-5

#205 Added percentage detection
  Face-Emotions-Recognition/Smile Percentage Detection/README.md
  Face-Emotions-Recognition/Smile Percentage Detection/deploy.prototxt
  Face-Emotions-Recognition/Smile Percentage Detection/detect_faces.py
  Face-Emotions-Recognition/Smile Percentage Detection/detect_faces_video.py
  Face-Emotions-Recognition/Smile Percentage Detection/face_detection_01.jpg
  Face-Emotions-Recognition/Smile Percentage Detection/face_detection_02.jpg
  Face-Emotions-Recognition/Smile Percentage Detection/how_to_train_face_detector.txt
  Face-Emotions-Recognition/Smile Percentage Detection/solver.prototxt
  Face-Emotions-Recognition/Smile Percentage Detection/test.prototxt
  Face-Emotions-Recognition/Smile Percentage Detection/train.prototxt
Labels: JWOC, easy

#215 Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/README.md
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/README.txt
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/cal_error.py
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/testset/images/0c32cffb644503b11aa9e8d23ea359d1.jpg
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/testset/images/0e0169ec0b8547bf625ed0ad0b9d6db2.jpg
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/testset/images/0e40a152da67398479ae41776ca6bed2.jpg
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/testset/images/0e424266c7d84fbed70adc06488626d9.jpg
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/testset/images/0e79395b87cb335aab6eb409123bd9fc.jpg
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/testset/landmarks/0c32cffb644503b11aa9e8d23ea359d1_l.npy
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/testset/landmarks/0e0169ec0b8547bf625ed0ad0b9d6db2_l.npy
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/testset/landmarks/0e40a152da67398479ae41776ca6bed2_l.npy
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/testset/landmarks/0e424266c7d84fbed70adc06488626d9_l.npy
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/testset/landmarks/0e79395b87cb335aab6eb409123bd9fc_l.npy
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/testset/landmarks_gt/0c32cffb644503b11aa9e8d23ea359d1.jpg.npy
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/testset/landmarks_gt/0e0169ec0b8547bf625ed0ad0b9d6db2.jpg.npy
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/testset/landmarks_gt/0e40a152da67398479ae41776ca6bed2.jpg.npy
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/testset/landmarks_gt/0e424266c7d84fbed70adc06488626d9.jpg.npy
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/testset/landmarks_gt/0e79395b87cb335aab6eb409123bd9fc.jpg.npy
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cal_error/testset/test.txt
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/cariface.py
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/data/README.txt
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/datagen.py
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/exp/README.txt
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/fig/examples.png
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/fig/examples2.png
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/model/README.txt
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/requirements.txt
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/test.sh
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/toy_example/1.npy
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/toy_example/README.txt
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/toy_example/mean_face.obj
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/toy_example/mesh_to_vertex.py
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/toy_example/vertex_to_mesh.py
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/train.py
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/train_options.py
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/update_contour/README.txt
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/update_contour/fit_indices.py
  Face Reconstruction/Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model/update_contour/parallel.txt
Labels: DWOC, Level-4

#224 Added Monocular 3D Face Reconstruction
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/LICENSE
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/README.md
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/__init__.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/data/test/image00008.jpg
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/data/test/image00499.jpg
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/data/test/image04275.jpg
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/data/test/image04328.jpg
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/requirements.txt
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/__init__.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/common/__init__.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/common/face_io.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/common/format_helper.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/common/parse_encoder.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/common/tf_io.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/common/visual_helper.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/data/__init__.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/data/data_loader_semi_unsupervised_skin.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/__init__.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/camera/__init__.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/camera/camera.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/camera/camera_augment.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/camera/camera_render.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/camera/rotation.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/camera_distribute/__init__.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/camera_distribute/camera_utils.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/covisible.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/face_align/__init__.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/face_align/align.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/face_align/align_facenet.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/face_align/gafr_std_align.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/face_align/generate_align_self.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/face_align/std_lm_pose.txt
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/geo_utils.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/gpmm/HDF5IO.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/gpmm/__init__.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/gpmm/bfm09_tf_uv.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/gpmm/trimesh_util.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/render/__init__.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/render/api_tf_mesh_render.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/render/lighting.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/render/tensor_render.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/geometry/render/trimesh_render.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/net/__init__.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/net/inception_resnet_v1.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_common/net/resnet_v1_3dmm.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_tfGraph/__init__.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_tfGraph/build_graph.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_tfGraph/decoder_multiView.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_tfGraph/deep_3dmm_decoder.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/src_tfGraph/deep_3dmm_loss.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/test_image.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/tools/__init__.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/tools/preprocess/__init__.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/tools/preprocess/crop_image_affine.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/tools/preprocess/detect_landmark.py
  Face Reconstruction/Self-Supervised Monocular 3D Face Reconstruction by Occlusion-Aware Multi-view Geometry Consistency/train_unsupervise.py
Labels: DWOC, Level-4

#226 Enhanced the README.md file.
  README.md
Labels: DWOC, Level-1

#213 Added README.md
  Face-Detection/README.md
  Face-Detection/imgs/celebrities.jpg
  Face-Detection/imgs/unknown.jpg
Labels: JWOC, easy
