Repository akshitagupta15june/Face-X, pull requests merged in 2021-12, with the labels that each got.

#987 New_Filter = Added (Christmas + Halloween) together
  Snapchat_Filters/Christmas+Halloween-filter/Happy(christmas+halloween).JPG
  Snapchat_Filters/Christmas+Halloween-filter/README.md
  Snapchat_Filters/Christmas+Halloween-filter/WIN_20211207_13_35_00_Pro.jpg
  Snapchat_Filters/Christmas+Halloween-filter/christmas-tree-hat.png
  Snapchat_Filters/Christmas+Halloween-filter/code.py
  Snapchat_Filters/Christmas+Halloween-filter/ghost-teeth.png
  Snapchat_Filters/Christmas+Halloween-filter/halloween.png
Labels: easy, CodePeak

#988 Snapchat Filters using OpenCV #66
  Snapchat_Filters/shiva_tilak_fliter/README.md
  Snapchat_Filters/shiva_tilak_fliter/haarcascade_frontalface_default.xml/haarcascade_frontalface_default.xml
  Snapchat_Filters/shiva_tilak_fliter/images/family with fliter.png
  Snapchat_Filters/shiva_tilak_fliter/images/family.png
  Snapchat_Filters/shiva_tilak_fliter/images/om5.png
  Snapchat_Filters/shiva_tilak_fliter/snapfliter_hemanth.ipynb
Labels: easy, CodePeak

#992 Added a new filter under "Add a "what is the day" snapchat filter #957 " issue
  Snapchat_Filters/DayandTime_Filter/Font/Bold & Stylish Calligraphy.ttf
  Snapchat_Filters/DayandTime_Filter/Images/final.png
  Snapchat_Filters/DayandTime_Filter/Images/original.png
  Snapchat_Filters/DayandTime_Filter/README.md
  Snapchat_Filters/DayandTime_Filter/dateandtime_filter.ipynb
Labels: Medium, CodePeak

#996 added face morph with opencv
  Awesome-face-operations/Face-Morphing/Face Morph/.ipynb_checkpoints/Face Morphing-checkpoint.ipynb
  Awesome-face-operations/Face-Morphing/Face Morph/Face Morphing.ipynb
  Awesome-face-operations/Face-Morphing/Face Morph/donald_trump.jpg
  Awesome-face-operations/Face-Morphing/Face Morph/donald_trump.jpg.txt
  Awesome-face-operations/Face-Morphing/Face Morph/hillary_clinton.jpg
  Awesome-face-operations/Face-Morphing/Face Morph/hillary_clinton.jpg.txt
  Awesome-face-operations/Face-Morphing/Face Morph/tri.txt
Labels: SWoC 2021, Under-Review
