Repository akshitagupta15june/Face-X, pull requests merged in 2021-03, with the labels that each got.

#234 updated readme of cartoonify Image folder
  Cartoonify Image/Cartoonify_face_image/readme.md
  Cartoonify Image/readme.md
Labels: SWoC 2021, SWoC10

#270 Update README.md
  Recognition-Algorithms/Ensemble_facial_recognition/README.md
Labels: Level0, gssoc21

#267 Updated Readme file
  Recognition-Algorithms/Recognition_using_mtcnn/Readme.md
Labels: GSSOC'21, easy

#266 Updating readme for Virtual Makeover
  Virtual_makeover/readme.md
Labels: GSSOC'21, easy

#263 Updated README.md file
  Recognition-Algorithms/README.md
Labels: GSSOC'21, easy

#253 Adding NasNet architecture
  Recognition-Algorithms/Recognition_using_NasNet/.gitignore
  Recognition-Algorithms/Recognition_using_NasNet/create_dataset.py
  Recognition-Algorithms/Recognition_using_NasNet/main.py
  Recognition-Algorithms/Recognition_using_NasNet/models/__init__.py
  Recognition-Algorithms/Recognition_using_NasNet/models/nasnet.py
  Recognition-Algorithms/Recognition_using_NasNet/output.py
  Recognition-Algorithms/Recognition_using_NasNet/readme.md
  Recognition-Algorithms/Recognition_using_NasNet/requirements.txt
Labels: Level3, gssoc21

#245 Eye-Blink Counter
  Face-Emotions-Recognition/Eye-Blink-Counter/EyeBlinkCount.py
  Face-Emotions-Recognition/Eye-Blink-Counter/LICENSE
  Face-Emotions-Recognition/Eye-Blink-Counter/README.md
  Face-Emotions-Recognition/Eye-Blink-Counter/haarcascade_eye.xml
  Face-Emotions-Recognition/Eye-Blink-Counter/haarcascade_frontalface_default.xml
  Face-Emotions-Recognition/Eye-Blink-Counter/images/eye_closed.jpg
  Face-Emotions-Recognition/Eye-Blink-Counter/images/eye_open.jpg
  Face-Emotions-Recognition/Eye-Blink-Counter/images/working.png
Labels: GSSOC'21, Medium

#238 Tried to make the code simpler
  Cartoonify Image/Cartoonify_face_image/Cartoonify-face_image.py
  Face-Swapping/Face_Swapping.py
  Face-Swapping/Sample images/Face_swap_2.jpg
  Face-Swapping/Sample images/Face_swap_3.jpg
  Face-Swapping/Sample images/face_swap_1.png
  Face-Swapping/readme.md
Labels: Level1, Level3, enhancement+documentation, gssoc21

#281 updated readme for issue-257
  Recognition-using-IOT/readme.md
Labels: Level-1, gssoc21

#293 algorithm of snapchat filter added.
  Snapchat_Filters/Detective Filter/README.md
Labels: Level0, gssoc21

#291 Added mask
  Face-Mask-Detection/Dataset.rar
  Face-Mask-Detection/Sample-images/Method.jpg
  Face-Mask-Detection/Sample-images/Sample_image_1.jpg
  Face-Mask-Detection/Sample-images/Sample_image_2.jpg
  Face-Mask-Detection/face-mask-detection-using-cnn.ipynb
  Face-Mask-Detection/readme.md
Labels: Level3, gssoc21

#295 Added code for face and eye detection
  Face-Detection/face and eye detection/code.py
  Face-Detection/face and eye detection/haarcascade_eye_tree_eyeglasses.xml
  Face-Detection/face and eye detection/haarcascade_frontalface_default.xml
  Face-Detection/face and eye detection/readme.txt
Labels: Level2, gssoc21

#303 Add the details about Resnet50 model
  Recognition-Algorithms/Recognition using ResNet50/Readme.md
Labels: Level0, gssoc21

#308 Updated README.md
  Face-Detection/face detection using caffe/README.md
Labels: Level1, gssoc21

#316 Improved Readme file for issue#274
  Cartoonify Image/Cartoonify_face_image/readme.md
Labels: Level1, gssoc21

#327 Added Sample Image and Readme
  Face-Mask-Detection/face-mask-detection-pytorch/Sample-Images/Sample-Image.png
  Face-Mask-Detection/face-mask-detection-pytorch/Sample-Images/model-image.png
  Face-Mask-Detection/face-mask-detection-pytorch/face-mask-detection-pytorch.ipynb
  Face-Mask-Detection/face-mask-detection-pytorch/readme.md
Labels: Level3, gssoc21

#332 added a readme for GUI of LBPH algo
  GUI_for_Face_Recognistion_using_LBPH_algo/readme.md
Labels: Level1, gssoc21

#338 Added flower crown and witch hat filter
  Snapchat_Filters/flower&witch_hat_filter/demo1.PNG
  Snapchat_Filters/flower&witch_hat_filter/demo3.PNG
  Snapchat_Filters/flower&witch_hat_filter/demo4.PNG
  Snapchat_Filters/flower&witch_hat_filter/filter1.py
  Snapchat_Filters/flower&witch_hat_filter/flower.jpg
  Snapchat_Filters/flower&witch_hat_filter/haarcascade_eye.xml
  Snapchat_Filters/flower&witch_hat_filter/haarcascade_frontalface_default.xml
  Snapchat_Filters/flower&witch_hat_filter/readme.md
  Snapchat_Filters/flower&witch_hat_filter/witch2.png
Labels: Level3, gssoc21

#340 Updated Cartoonify-face_image.py for issue#319
  Cartoonify Image/Cartoonify_face_image/Cartoonify-face_image.py
Labels: Level0, gssoc21

#341 Updates Readme by adding video for issue#319
  Cartoonify Image/Cartoonify_face_image/readme.md
Labels: Level0, gssoc21

#349 Related to Changes requested #346 issue
  Awesome-face-operations/Ghost Image/Images/Ghost Photo.jpg
  Awesome-face-operations/Ghost Image/Images/photo.jpg
  Awesome-face-operations/Ghost Image/README.md
  Awesome-face-operations/Ghost Image/ghost_image.py
  Images/Ghost Photo.jpg
  Images/photo.jpg
Labels: Level3, gssoc21

#355 Improved Readme file and Python Notebook regarding face-mask-detection model using Pytorch
  Face-Mask-Detection/face-mask-detection-pytorch/face-mask-detection-pytorch.ipynb
  Face-Mask-Detection/face-mask-detection-pytorch/readme.md
Labels: Level1, gssoc21

#362 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: Level1, gssoc21

#361 Adding Recognition Algorithm using LDA
  Recognition-Algorithms/Recognition using LDA/FaceRecognitionUsingLDA.py
  Recognition-Algorithms/Recognition using LDA/Images/Faces.png
  Recognition-Algorithms/Recognition using LDA/Images/FisherFaces.png
  Recognition-Algorithms/Recognition using LDA/Images/Report.png
  Recognition-Algorithms/Recognition using LDA/README.md
Labels: Level3, gssoc21

#359 added code implementation for facial recognition using SURF.
  Recognition-Algorithms/Recognition using SURF/Readme.md
  Recognition-Algorithms/Recognition using SURF/face_recognition_using_surf.ipynb
  Recognition-Algorithms/Recognition using SURF/img1.jpg
  Recognition-Algorithms/Recognition using SURF/img2.jpg
Labels: Level3, gssoc21

#358 Added code and readme.md file with sample output images for Pencil Sk…
  Awesome-face-operations/Pencil Sketch/pencil_sketch_code.py
  Awesome-face-operations/Pencil Sketch/readme.md
Labels: Level3, gssoc21

#384 issue#339 Face Mask Detection VGG16 project added
  Face-Mask-Detection/face-mask-detection-vgg16/Face_Mask_Detection_VGG16.ipynb
  Face-Mask-Detection/face-mask-detection-vgg16/Readme.md
  Face-Mask-Detection/face-mask-detection-vgg16/Sample-images/dataset.png
  Face-Mask-Detection/face-mask-detection-vgg16/Sample-images/mask-group.jpg
  Face-Mask-Detection/face-mask-detection-vgg16/Sample-images/vgg16.png
Labels: Level3, gssoc21

#385 modified the readme file of LDA
  Recognition-Algorithms/Recognition using LDA/README.md
Labels: Level1, gssoc21

#390 Cartoonify an Image Using opencv
  Cartoonify Image/Cartoonifying using OpenCV/Cartoonify.py
  Cartoonify Image/Cartoonifying using OpenCV/Readme.md
Labels: Level1, gssoc21

#391 Added Face Recognition Using Dlib
  Recognition-Algorithms/Recognition Using Dlib/Readme.md
  Recognition-Algorithms/Recognition Using Dlib/Unknown.jpg
  Recognition-Algorithms/Recognition Using Dlib/face.py
  Recognition-Algorithms/Recognition Using Dlib/face_recognition/__init__.py
  Recognition-Algorithms/Recognition Using Dlib/face_recognition/api.py
  Recognition-Algorithms/Recognition Using Dlib/face_recognition/face_detection_cli.py
  Recognition-Algorithms/Recognition Using Dlib/face_recognition/face_recognition_cli.py
  Recognition-Algorithms/Recognition Using Dlib/images/Bill_Gates.jpg
  Recognition-Algorithms/Recognition Using Dlib/images/Mark_Zuckerberg.jpg
Labels: Level3, gssoc21

#393 Resolving issue #373 - Emotion Detection
  .vscode/settings.json
  Face-Emotions-Recognition/Emotion-recognition-with-GUI/Readme.md
  Face-Emotions-Recognition/Emotion-recognition-with-GUI/app.py
  Face-Emotions-Recognition/Emotion-recognition-with-GUI/emotion-detector-optimal.ipynb
  Face-Emotions-Recognition/Emotion-recognition-with-GUI/haarcascade_frontalface_default.xml
  Face-Emotions-Recognition/Emotion-recognition-with-GUI/images/Capture - 2.PNG
  Face-Emotions-Recognition/Emotion-recognition-with-GUI/images/Capture.PNG
  Face-Emotions-Recognition/Emotion-recognition-with-GUI/images/Icons8-Ios7-Logos-Google-Drive-Copyrighted.ico
  Face-Emotions-Recognition/Emotion-recognition-with-GUI/images/Screenshot (154).png
  Face-Emotions-Recognition/Emotion-recognition-with-GUI/images/Screenshot (155).png
  Face-Emotions-Recognition/Emotion-recognition-with-GUI/images/Screenshot (156).png
Labels: Level3, gssoc21

#396 Issue 366 image segmentation: Added Implementation of Image segmentation using color spaces and opencv
  Awesome-face-operations/image-segmentation/image_segmenation1.py
  Awesome-face-operations/image-segmentation/images/BGR_IMAGE.PNG
  Awesome-face-operations/image-segmentation/images/GRAY_IMAGE.PNG
  Awesome-face-operations/image-segmentation/images/HSV_IMAGE.PNG
  Awesome-face-operations/image-segmentation/images/RBG_IMAGE.PNG
  Awesome-face-operations/image-segmentation/images/demo1.PNG
  Awesome-face-operations/image-segmentation/images/demo2.PNG
  Awesome-face-operations/image-segmentation/readme.md
  Awesome-face-operations/image-segmentation/train/emma1.jpg
  Awesome-face-operations/image-segmentation/train/emma2.jpg
  Awesome-face-operations/image-segmentation/train/emma3.jpg
  Awesome-face-operations/image-segmentation/train/emma4.jpg
  Awesome-face-operations/image-segmentation/train/emma5.jpg
Labels: Level3, gssoc21

#401 Improved README for face detection using dlib hog
  Face-Detection/Face detection using dlib hog/README.md
Labels: Level1, gssoc21

#416 Added mosaic effect
  Awesome-face-operations/Mosaic-Effect/Mosaic.py
  Awesome-face-operations/Mosaic-Effect/images (1).jpg
  Awesome-face-operations/Mosaic-Effect/images.jpg
  Awesome-face-operations/Mosaic-Effect/readme.md
Labels: Level3, gssoc21

#415 Improved readme of Awesome-face-operations
  Awesome-face-operations/Readme.md
Labels: Level-1, gssoc21

#410 Updated GUI design for the application
  Cartoonify Image/Cartoonify-GUI/Updated GUI.png
  Cartoonify Image/Cartoonify-GUI/background.png
  Cartoonify Image/Cartoonify-GUI/cartoonify-gui.py
Labels: Level1, gssoc21

#424 Add Pencil Sketch in Python using OpenCV Readme File Update
  Awesome-face-operations/Pencil Sketch/Pencil_Image/Title .png
  Awesome-face-operations/Pencil Sketch/Pencil_Image/book-pencil.png
  Awesome-face-operations/Pencil Sketch/Pencil_Image/girl_pencil.jpg
  Awesome-face-operations/Pencil Sketch/Pencil_Image/pencil2.png
  Awesome-face-operations/Pencil Sketch/Pencil_Image/pencil4.png
  Awesome-face-operations/Pencil Sketch/readme.md
Labels: Level1, gssoc21

#428 Ghost Image/images path addition to get rid of uploading them
  Awesome-face-operations/Ghost Image/README.md
  Awesome-face-operations/Ghost Image/ghost_image.py
Labels: Level0, gssoc21

#431 Improved readme file of Face-mask-detection
  Face-Mask-Detection/Readme.md
Labels: Level1, gssoc21

#433 Added image stitching
  Awesome-face-operations/Image-Stiching/Sample-img.jpg
  Awesome-face-operations/Image-Stiching/image_stiching.py
  Awesome-face-operations/Image-Stiching/readme.md
Labels: Level3, gssoc21

#436 Detective Filter Readme file Update Image path
  CONTRIBUTORS.md
  Snapchat_Filters/Detective Filter/README.md
Labels: Level0, gssoc21
