Repository akshitagupta15june/Face-X, pull requests merged in 2022-03, with the labels that each got.

#1074 Changed The Read Me
  Readme.md
Labels: Level1, GSSoC22

#1078 Update requirements
  requirements.txt
Labels: Level1, GSSoC22

#1077 Added a bullnose filter
  Snapchat_Filters/Bullnose_filter/bullnose.png
  Snapchat_Filters/Bullnose_filter/main_file.py
  Snapchat_Filters/Bullnose_filter/nosess.PNG
  Snapchat_Filters/Bullnose_filter/readme.md
Labels: Level2, GSSoC22

#1085 Newly Implemented Algorithms Added to Comparison table in Readme
  Recognition-Algorithms/README.md
Labels: Level1, GSSoC22

#1083 Optimizing eigen values & eigen vectors computation
  Recognition-Algorithms/Recognition using PCA/main.py
Labels: Level1, GSSoC22

#1087 Implemented Face Alignment
  Awesome-face-operations/Face-Alignment/.gitignore
  Awesome-face-operations/Face-Alignment/README.md
  Awesome-face-operations/Face-Alignment/facealigner/__init__.py
  Awesome-face-operations/Face-Alignment/facealigner/facealigner.py
  Awesome-face-operations/Face-Alignment/facealigner/helpers.py
  Awesome-face-operations/Face-Alignment/facial_landmarks.py
  Awesome-face-operations/Face-Alignment/main.py
  Awesome-face-operations/Face-Alignment/outputs/output.gif
Labels: Level2, GSSoC22

#1088 added faceDetection algorithm
  Face-Detection/faceDetection using face_recognition library/README.md
  Face-Detection/faceDetection using face_recognition library/faceDetection.py
Labels: Under-Review, GSSoC22

#1090 Create TowerBlink (updated)
  Face-X-Gaming/TowerBlink/README.md
  Face-X-Gaming/TowerBlink/main.py
  Face-X-Gaming/TowerBlink/requirements.txt
Labels: Level3, GSSoC22

#1091 Gssoc issue1
  Awesome-face-operations/Face-Morphing/readme.md
  Awesome-face-operations/Readme.md
Labels: Under-Review, GSSoC22

#1094 Updated ReadMe.md
  Face-X-Gaming/Readme.md
Labels: Level2, GSSoC22

#1104 Cartoon
  Cartoonify-Image/Differentiate between Human and Cartoon Faces/Assets/cartoon.jpeg
  Cartoonify-Image/Differentiate between Human and Cartoon Faces/Assets/image.webp
  Cartoonify-Image/Differentiate between Human and Cartoon Faces/Media/blurred_hsv.jpeg
  Cartoonify-Image/Differentiate between Human and Cartoon Faces/Media/image.webp
  Cartoonify-Image/Differentiate between Human and Cartoon Faces/Media/img_hsv.jpeg
  Cartoonify-Image/Differentiate between Human and Cartoon Faces/Media/new.jpeg
  Cartoonify-Image/Differentiate between Human and Cartoon Faces/README.md
  Cartoonify-Image/Differentiate between Human and Cartoon Faces/cartoon.py
  Cartoonify-Image/Differentiate between Human and Cartoon Faces/requirements.txt
Labels: Under-Review, Level3, GSSoC22

#1119 issue#1115 virtual facial jewellery
  Virtual_makeover/Facial-Jewellery/README.md
  Virtual_makeover/Facial-Jewellery/Virtual-ForeheadDot/input.png
  Virtual_makeover/Facial-Jewellery/Virtual-ForeheadDot/output.png
  Virtual_makeover/Facial-Jewellery/Virtual-ForeheadDot/virtual_forehead_dot.ipynb
  Virtual_makeover/Facial-Jewellery/Virtual-NoseStud/input.png
  Virtual_makeover/Facial-Jewellery/Virtual-NoseStud/output.png
  Virtual_makeover/Facial-Jewellery/Virtual-NoseStud/virtual_nose_stud.ipynb
Labels: Under-Review, GSSoC22
