Repository akshitagupta15june/Face-X, pull requests merged in 2023-02, with the labels that each got.

#1357 Updated README.md
  Face-X-Gaming/Youtube Controller/README.md
Labels: Easy, JWOC

#1374 Histogram-Equalization added
  Awesome-face-operations/Histogram-Equalization/.ipynb_checkpoints/Histogram_Equalization-checkpoint.ipynb
  Awesome-face-operations/Histogram-Equalization/Data/001.jpeg
  Awesome-face-operations/Histogram-Equalization/Histogram_Equalization.ipynb
  Awesome-face-operations/Histogram-Equalization/Readme.md
Labels: Medium, JWOC

#1375 Flappy Bird Game using Face Recognition
  Face-X-Gaming/FlappyBird/ReadMe.md
  Face-X-Gaming/FlappyBird/bird_sprite.png
  Face-X-Gaming/FlappyBird/canonical_face_model_uv_visualization.png
  Face-X-Gaming/FlappyBird/main.py
  Face-X-Gaming/FlappyBird/pipe_sprite_single.png
  Face-X-Gaming/Readme.md
  Face-X-Web/Face-Mask-Detection/ReadMe.md
  Face-X-Web/Face-Mask-Detection/__pycache__/facex.cpython-310.pyc
  Face-X-Web/Face-Mask-Detection/app.py
Labels: SWOC, SwoC30
