Repository akshitagupta15june/Face-X, pull requests merged in 2023-07, with the labels that each got.

#1567 RedBlackSunglassses
  Snapchat_Filters/RedBlackAntGoogles/README.md
  Snapchat_Filters/RedBlackAntGoogles/main.py
  Snapchat_Filters/RedBlackAntGoogles/sunglass.png
Labels: Level2, gssoc23

#1611 Face-X web given a new look
  Face-X-Web/Frontend/index.html
  Face-X-Web/Frontend/style.css
  Face-X-Web/Frontend/styles2.css
  Face-X-Web/Frontend/upload.html
Labels: Level3, gssoc23

#1617 Added Funny Snapchat filter: Cartoon filter
  Snapchat_Filters/CartoonFilter/README.md
  Snapchat_Filters/CartoonFilter/filter.py
  Snapchat_Filters/CartoonFilter/ouput.png
  Snapchat_Filters/CartoonFilter/output.png
  Snapchat_Filters/CartoonFilter/requirements.txt
Labels: Level2, gssoc23

#1623 Add files via upload
  Snapchat_Filters/butterfly_world/README.md
  Snapchat_Filters/butterfly_world/anamika.py
  Snapchat_Filters/butterfly_world/butter3.png
  Snapchat_Filters/butterfly_world/glass3.png
  Snapchat_Filters/butterfly_world/m1.png
  Snapchat_Filters/butterfly_world/screenshots/butterfly_filter.png
  Snapchat_Filters/butterfly_world/screenshots/butterfly_filter2.png
  Snapchat_Filters/butterfly_world/screenshots/butterfly_filter3.png
Labels: SSOC

#1624 Added cool Snapchat filter: Kaleidoscope Filter
  Snapchat_Filters/Kaleidoscope Filter/README.md
  Snapchat_Filters/Kaleidoscope Filter/filter.py
  Snapchat_Filters/Kaleidoscope Filter/output.png
  Snapchat_Filters/Kaleidoscope Filter/requirements.txt
Labels: SSOC
